### ISSUE TITLE
Broken transient_prompt: unable to create text based on template

### ISSUE THREAD

**Issue by impopular-guy** [JanDeDobbeleer/oh-my-posh#3218] opened 2022-12-17 20:32 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I modified the `transient_prompt` of an existing theme `pure.omp.json` into the following:

```json
"transient_prompt": {
    "template": "<#81A1C1>{{ .Folder }}</>{{if .Segments.Git }} <#6C6C6C>{{ .Segments.Git.HEAD }}</> <#FFAFD7>* \u002b{{ .Segments.Git.Working.Added }} \u002d{{ .Segments.Git.Working.Deleted }} \u007e{{ .Segments.Git.Working.Modified }} \u003f{{ .Segments.Git.Working.Untracked }}</> <#8BB842>\uf046 \u002b{{ .Segments.Git.Staging.Added }} \u002d{{ .Segments.Git.Staging.Deleted }} \u007e{{ .Segments.Git.Staging.Modified }} \u003f{{ .Segments.Git.Staging.Untracked }}</>{{ if gt .Segments.Git.StashCount 0 }} <#1A7BC9>\uf692 {{ .Segments.Git.StashCount }}</>{{ end }}{{end}}{{if .Segments.Executiontime }} <#A3BE8C>({{ .Segments.Executiontime.FormattedMs }})</>{{end}} <#B48EAD>\u276f</>"
  },
```

Got the following response:
![second_case_if_Screenshot 2022-12-18 014304](https://user-images.githubusercontent.com/34854740/208264886-0417af65-aec1-484d-8350-bba541ae45cd.png)

---

However, I noticed the if I remove `{{ if gt .Segments.Git.StashCount 0 }}` it works fine.

```json
"transient_prompt": {
    "template": "<#81A1C1>{{ .Folder }}</>{{if .Segments.Git }} <#6C6C6C>{{ .Segments.Git.HEAD }}</> <#FFAFD7>* \u002b{{ .Segments.Git.Working.Added }} \u002d{{ .Segments.Git.Working.Deleted }} \u007e{{ .Segments.Git.Working.Modified }} \u003f{{ .Segments.Git.Working.Untracked }}</> <#8BB842>\uf046 \u002b{{ .Segments.Git.Staging.Added }} \u002d{{ .Segments.Git.Staging.Deleted }} \u007e{{ .Segments.Git.Staging.Modified }} \u003f{{ .Segments.Git.Staging.Untracked }}</> <#1A7BC9>\uf692 {{ .Segments.Git.StashCount }}</>{{end}}{{if .Segments.Executiontime }} <#A3BE8C>({{ .Segments.Executiontime.FormattedMs }})</>{{end}} <#B48EAD>\u276f</>"
  },
```
![second_case_no_if_Screenshot 2022-12-18 014114](https://user-images.githubusercontent.com/34854740/208264975-bd0f9b31-3b73-449f-8594-7c97cc746353.png)

### Theme

[`pure.omp.json`](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/pure.omp.js)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
> oh-my-posh debug

Version: 12.26.8

Segments:

ConsoleTitle(true)   -   0 ms -  ~\Documents\ProjectFolder\cloth_simulation
session(true)        -   1 ms - dhritiss
path(true)           -   1 ms - ~\Documents\ProjectFolder\cloth_simulation
git(true)            -  40 ms - main ≢*?1 ~1
executiontime(false) -   0 ms -
exit(true)           -   0 ms - ❯

Run duration: 56.0285ms

Cache path: C:\Users\dhrit\AppData\Local\oh-my-posh

Config path: C:\Users\dhrit\AppData\Local\Programs\oh-my-posh\themes\puremod.omp.json

Logs:

2022/12/18 01:48:01 Getenv
C:\Users\dhrit\AppData\Local
2022/12/18 01:48:01 Getenv: 0s, args: LOCALAPPDATA
2022/12/18 01:48:01 CachePath: 0s
2022/12/18 01:48:01 Getenv
C:\Users\dhrit\AppData\Local\Programs\oh-my-posh\themes\puremod.omp.json
2022/12/18 01:48:01 Getenv: 0s, args: POSH_THEME
2022/12/18 01:48:01 Shell
process name: powershell.exe
2022/12/18 01:48:01 Shell: 7.8854ms
2022/12/18 01:48:01 resolveConfigPath: 7.8854ms
2022/12/18 01:48:01 Init: 10.9966ms
2022/12/18 01:48:01 Flags: 0s
2022/12/18 01:48:01 config.loadConfig: 592µs
2022/12/18 01:48:01 Flags: 0s
2022/12/18 01:48:01 Getenv

2022/12/18 01:48:01 Getenv: 0s, args: OMP_CACHE_DISABLED
2022/12/18 01:48:01 WindowsRegistryKeyValue: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC43C9419
2022/12/18 01:48:01 Root: 0s
2022/12/18 01:48:01 Shell: 0s
2022/12/18 01:48:01 ErrorCode: 0s
2022/12/18 01:48:01 IsWsl: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 User
dhritiss
2022/12/18 01:48:01 User: 0s
2022/12/18 01:48:01 Host
tituHPPC
2022/12/18 01:48:01 Host: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 TemplateCache: 518.5µs
2022/12/18 01:48:01 Flags: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 Getenv

2022/12/18 01:48:01 Getenv: 0s, args: SSH_CONNECTION
2022/12/18 01:48:01 Getenv

2022/12/18 01:48:01 Getenv: 0s, args: SSH_CLIENT
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 Shell: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 Shell: 0s
2022/12/18 01:48:01 Shell: 0s
2022/12/18 01:48:01 Flags: 0s
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 PathSeparator: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 IsWsl: 0s
2022/12/18 01:48:01 StackCount: 0s
2022/12/18 01:48:01 isWriteable
not current user or in group
2022/12/18 01:48:01 isWriteable
current user is member of S-1-5-32-544
2022/12/18 01:48:01 isWriteable
WRITE_DAC
WRITE_OWNER
SYNCHRONIZE
DELETE
READ_CONTROL
2022/12/18 01:48:01 isWriteable
user has write access
2022/12/18 01:48:01 DirIsWritable: 521.7µs
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 Shell: 0s
2022/12/18 01:48:01 Flags: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 CommandPath
C:\Program Files\Git\cmd\git.exe
2022/12/18 01:48:01 CommandPath: 6.1955ms, args: git.exe
2022/12/18 01:48:01 HasCommand: 6.1955ms, args: git.exe
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 HasParentFilePath: 0s, args: .git
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 Getenv

2022/12/18 01:48:01 Getenv: 0s, args: POSH_GIT_STATUS
2022/12/18 01:48:01 RunCommand
# branch.oid 483cdb894ca1f4fdd4802416a4fcc05c876246aa
# branch.head main
1 .M N... 100644 100644 100644 7fcab9fd97f7c790f2d90c668baeabcd0e834d6e 7fcab9fd97f7c790f2d90c668baeabcd0e834d6e main.go? newfile.txt
2022/12/18 01:48:01 RunCommand: 33.0719ms, args: git.exe -C C:/Users/dhrit/Documents/ProjectFolder/cloth_simulation --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --branch --porcelain=2
2022/12/18 01:48:01 HasFolder
false
2022/12/18 01:48:01 HasFolder: 0s, args: C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation\.git/rebase-merge
2022/12/18 01:48:01 HasFolder
false
2022/12/18 01:48:01 HasFolder: 0s, args: C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation\.git/rebase-apply
2022/12/18 01:48:01 HasFilesInDir
false
2022/12/18 01:48:01 HasFilesInDir: 0s, args: MERGE_MSG
2022/12/18 01:48:01 HasFilesInDir
false
2022/12/18 01:48:01 HasFilesInDir: 0s, args: CHERRY_PICK_HEAD
2022/12/18 01:48:01 HasFilesInDir
false
2022/12/18 01:48:01 HasFilesInDir: 0s, args: REVERT_HEAD
2022/12/18 01:48:01 HasFilesInDir
false
2022/12/18 01:48:01 HasFilesInDir: 0s, args: sequencer/todo
2022/12/18 01:48:01 FileContent
open C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation\.git/logs/refs/stash: The system cannot find the file specified.
2022/12/18 01:48:01 FileContent: 506.9µs, args: C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation\.git/logs/refs/stash
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 Shell: 0s
2022/12/18 01:48:01 Flags: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 ExecutionTime: 0s
2022/12/18 01:48:01 Flags: 0s
2022/12/18 01:48:01 Pwd
C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation
2022/12/18 01:48:01 Pwd: 0s
2022/12/18 01:48:01 Home
C:\Users\dhrit
2022/12/18 01:48:01 GOOS: 0s
2022/12/18 01:48:01 ErrorCode: 0s
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 Shell: 0s
2022/12/18 01:48:01 TemplateCache: 0s
2022/12/18 01:48:01 Getenv
C:\Users\dhrit\AppData\Local
2022/12/18 01:48:01 Getenv: 0s, args: LOCALAPPDATA
2022/12/18 01:48:01 CachePath: 0s
2022/12/18 01:48:01 Flags: 0s
```
```

**Comment by JanDeDobbeleer** [comment] 2022-12-17 20:42
@impopular-guy not a bug though, `{{if .Segments.Git }}` is incorrect syntax. You're looking for this: `{{ if .Segments.Contains \"Git\" }}`. See [here](https://ohmyposh.dev/docs/configuration/templates#cross-segment-template-properties) (bottom of that part).

Same for `Executiontime`.

**Comment by impopular-guy** [comment] 2022-12-17 20:56
@JanDeDobbeleer Hi, I corrected the syntax but this doesn't solve the issue at hand. The error is due to `{{ if gt .Segments.Git.StashCount 0 }}` piece of code. It seems like nested if is a problem

Is there another syntax to see if value is greater than zero?

**Comment by JanDeDobbeleer** [comment] 2022-12-17 21:00
@impopular-guy ah, sorry missed that somehow. Probably a bit tired here. Let me check real quick. You can add the same template to a temporary `text` segment to see the actual error in `oh-my-posh debug`.

**Comment by impopular-guy** [comment] 2022-12-17 21:15
> @impopular-guy ah, sorry missed that somehow. Probably a bit tired here. Let me check real quick. You can add the same template to a temporary `text` segment to see the actual error in `oh-my-posh debug`.

It's fine. Take your time. I tried adding a temp `text` segment. It worked fine. Problem present only in `transient_prompt`. All i can see in debug is below which was present before as well.
```
2022/12/18 01:48:01 FileContent
open C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation\.git/logs/refs/stash: The system cannot find the file specified.
2022/12/18 01:48:01 FileContent: 506.9µs, args: C:\Users\dhrit\Documents\ProjectFolder\cloth_simulation\.git/logs/refs/stash
```

**Comment by JanDeDobbeleer** [comment] 2022-12-17 21:28
@impopular-guy I can reproduce this now, will have a look as it makes no sense yet tbh.

**Comment by JanDeDobbeleer** [comment] 2022-12-17 21:59
@impopular-guy found out why this happens, the cache doesn't parse the Segments as they are (because that would be a lot of overhead) so StashCount returns as a float64 instead of an int. Replace with the following and it's fixed in the meantime:

```json
{{ if gt .Segments.Git.StashCount (float64 0) }}
```

I will add that to the docs as overriding all builtin functions to handle this is also insane.

**Closed as completed** 2022-12-18 14:02 UTC
Labels: 🐛 bug
