### ISSUE TITLE
Path shortening misbehaving on msys2

### ISSUE THREAD

**Issue by flamewing** [JanDeDobbeleer/oh-my-posh#1415] opened 2021-12-12 16:29 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I recently updated from version 5.3.0 to 6.31.0, and I noticed a regression on msys2 regarding path shortening. In 5.3.0, using the pixel robots theme, I had this prompt on a given directory:

![image](https://user-images.githubusercontent.com/6319024/145719402-05f48c38-e79a-4837-85aa-b3114d45b6dd.png)

Whereas in 6.31.0, I get this prompt:

![image](https://user-images.githubusercontent.com/6319024/145719443-a009447f-2b10-4429-ae1a-c578da7a1b3f.png)

If I run it on WSL or PowerShell, I get the correct shortening; if I use this command:

```bash
PROMPT_COMMAND='PS1=$(oh-my-posh.exe -shell bash --config ~/.poshthemes/pixelrobots.omp.json)'
```

I also get the correct shortening. But if I use a command closer to what is generated by `oh-my-posh.exe -init -shell bash -config ~/.poshthemes/pixelrobots.omp.json`, namely this:

```bash
PROMPT_COMMAND='PS1=$(oh-my-posh.exe -shell bash -config ~/.poshthemes/pixelrobots.omp.json -pwd "$PWD")'
```

then I get the incorrectly shortened version shown above.

Of note:

![image](https://user-images.githubusercontent.com/6319024/145720440-60327c18-89ca-4ef8-b32d-9561bbf08db5.png)

Note the types of slashes on the path link portion of those 3 commands.

For what is worth. I am mostly using Windows Terminal recently, but it also happens on MinTTY.

### Theme

PixelRobots with an extra segment, but it also happens on other random themes I tried.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```shell
[1mVersion:[0m 6.31.0

[1mSegments:[0m

ConsoleTitle(true) -   0 ms - MINGW64 :: Sonic-Classic-Heroes
text(false)    -   0 ms - 
kubectl(false) -   2 ms - 
az(false)      -   2 ms - 
os(true)       -   0 ms - [38;2;47;47;47m▓[0m[48;2;47;47;47m[38;2;38;198;218m [0m[48;2;47;47;47m[38;2;38;198;218m[0m[48;2;47;47;47m[38;2;255;234;0m [0m
envvar(true)   -   0 ms - [48;2;47;47;47m[38;2;38;198;218m [0m[48;2;47;47;47m[38;2;38;198;218mMINGW64[0m[48;2;47;47;47m[38;2;255;234;0m [0m
session(true)  -   0 ms - [48;2;47;47;47m[38;2;255;234;0m [0m[48;2;47;47;47m[38;2;255;234;0mflamewing[0m[48;2;47;47;47m[38;2;255;234;0m [0m
root(false)    -   0 ms - 
path(true)     -   0 ms - [48;2;47;47;47m[38;2;242;242;0m  [0m[48;2;47;47;47m[38;2;250;250;250m]8;;file://D:\Documents\Dev\Source\sonicretro\Sonic-Classic-Heroes\D:[0m[48;2;47;47;47m[38;2;255;234;0m [0m[48;2;47;47;47m[38;2;181;178;194m [0m[48;2;47;47;47m[38;2;255;234;0m [0m[48;2;47;47;47m[38;2;250;250;250mSonic-Classic-Heroes]8;;\[0m[48;2;47;47;47m[38;2;250;250;250m [0m
git(true)      - 236 ms - [48;2;47;47;47m[38;2;255;234;0m [0m[48;2;47;47;47m[38;2;255;234;0m master ≡  2[0m[48;2;47;47;47m[38;2;255;234;0m [0m
text(false)    -   0 ms - 
text(true)     -   0 ms - [38;2;255;234;0m [0m[38;2;255;234;0m❯[0m[38;2;255;234;0m [0m

[1mRun duration:[0m 243.6579ms

[1mLogs:[0m

2021/12/12 17:24:15 debug: getenv
C:\Users\marzo\AppData\Local
2021/12/12 17:24:15 getenv duration: 0s, args: LOCALAPPDATA
2021/12/12 17:24:15 getCachePath duration: 0s, args: 
2021/12/12 17:24:15 getArgs duration: 0s, args: 
2021/12/12 17:24:15 getArgs duration: 0s, args: 
2021/12/12 17:24:15 getShellName duration: 0s, args: 
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: OMP_CACHE_DISABLED
2021/12/12 17:24:15 isRunningAsRoot duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getShellName duration: 0s, args: 
2021/12/12 17:24:15 getCurrentUser duration: 0s, args: 
2021/12/12 17:24:15 getHostName duration: 0s, args: 
2021/12/12 17:24:15 debug: getenv
MINGW64
2021/12/12 17:24:15 getenv duration: 0s, args: MSYSTEM
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 isRunningAsRoot duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getShellName duration: 0s, args: 
2021/12/12 17:24:15 getCurrentUser duration: 0s, args: 
2021/12/12 17:24:15 getHostName duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 error: hasCommand
exec: "kubectl": executable file not found in %PATH%
2021/12/12 17:24:15 hasCommand duration: 2.1094ms, args: kubectl
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: AZ_ENVIRONMENT_NAME
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: AZ_USER_NAME
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: AZ_SUBSCRIPTION_ID
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: AZ_ACCOUNT_NAME
2021/12/12 17:24:15 error: hasCommand
exec: "az": executable file not found in %PATH%
2021/12/12 17:24:15 hasCommand duration: 2.0688ms, args: az
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 debug: getenv
MINGW64
2021/12/12 17:24:15 getenv duration: 0s, args: MSYSTEM
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: SSH_CONNECTION
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: SSH_CLIENT
2021/12/12 17:24:15 getCurrentUser duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 getHostName duration: 0s, args: 
2021/12/12 17:24:15 isRunningAsRoot duration: 0s, args: 
2021/12/12 17:24:15 debug: getenv

2021/12/12 17:24:15 getenv duration: 0s, args: POSH_SESSION_DEFAULT_USER
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 isRunningAsRoot duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getArgs duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getArgs duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 isWsl duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getRuntimeGOOS duration: 0s, args: 
2021/12/12 17:24:15 hasCommand duration: 516.5µs, args: git.exe
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 hasParentFilePath duration: 0s, args: .git
2021/12/12 17:24:15 debug: runCommand
# branch.oid 5cb87489f1070e06fa7c162973e1f8365f3e2474
# branch.head master
# branch.upstream origin/master
# branch.ab +0 -0
? _inc/KosinskiPlus.asm
? _incObj/Players/TeamSonic/
? art/size_of_dir.sh
? art/temp.bmp
? art/temp.png
? art/uncompressed/Players/wechnia.sh
? bin/fdp2bin.cc
? compile_commands.json
? deform/
? levsel.bin
? objtest.asm
? pixelrobots.png
? processcycles.sh
? reopen-1.sh
? reopen-2.sh
? restore_tabs_left.sh
? restore_tabs_right.sh
? sch-data.lua
? scheroes.safe.bin
? substcycles.sh
? unredirectbranch.sh
2021/12/12 17:24:15 runCommand duration: 236.2369ms, args: git.exe -C  --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --branch --porcelain=2
2021/12/12 17:24:15 hasFolder duration: 0s, args: D:\Documents\Dev\Source\sonicretro\Sonic-Classic-Heroes\.git/rebase-merge
2021/12/12 17:24:15 hasFolder duration: 0s, args: D:\Documents\Dev\Source\sonicretro\Sonic-Classic-Heroes\.git/rebase-apply
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 hasFilesInDir duration: 0s, args: MERGE_MSG
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 hasFilesInDir duration: 0s, args: CHERRY_PICK_HEAD
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 hasFilesInDir duration: 0s, args: REVERT_HEAD
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 hasFilesInDir duration: 0s, args: sequencer/todo
2021/12/12 17:24:15 getFileContent duration: 0s, args: D:\Documents\Dev\Source\sonicretro\Sonic-Classic-Heroes\.git/logs/refs/stash
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 isRunningAsRoot duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getShellName duration: 0s, args: 
2021/12/12 17:24:15 getCurrentUser duration: 0s, args: 
2021/12/12 17:24:15 getHostName duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 isRunningAsRoot duration: 0s, args: 
2021/12/12 17:24:15 getcwd duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getPathSeperator duration: 0s, args: 
2021/12/12 17:24:15 getShellName duration: 0s, args: 
2021/12/12 17:24:15 getCurrentUser duration: 0s, args: 
2021/12/12 17:24:15 getHostName duration: 0s, args:
```

**Comment by lnu** [comment] 2021-12-13 06:05
is it me or the first two screenshots are the same?
And is it no the opposite, like it was not exactly as it should have been with the old version and now it outouts the path as configured in the theme? you can replace the `>` by something else to match what you desire.
https://ohmyposh.dev/docs/themes#pixelrobots

**Comment by flamewing** [comment] 2021-12-13 21:53
Hm, I don't know what happened to the first screenshot; in the preview, it displayed the correct screenshot, showing a difference between the two. Anyway, here is a screenshot using a workaround:

![image](https://user-images.githubusercontent.com/6319024/145893641-49600838-c5a1-4bbb-bac6-df93856b1d95.png)

This is identical to what it was on the old version, and was obtained by using the following patched version of `_omp_hook`:

```bash
function _omp_hook() {
    local ret=$?

    omp_stack_count=$((${#DIRSTACK[@]} - 1))
    omp_elapsed=-1
    if [[ -f "$TIMER_START" ]]; then
        omp_now=$(D:/msys64/usr/bin/oh-my-posh.exe --millis)
        omp_start_time=$(cat "$TIMER_START")
        omp_elapsed=$((omp_now-omp_start_time))
        rm -f "$TIMER_START"
    fi
    PS1="$(D:/msys64/usr/bin/oh-my-posh.exe --config="$POSH_THEME" --shell=bash --error="$ret" --execution-time="$omp_elapsed" --stack-count="$omp_stack_count" --pwd="$(cygpath -w "$PWD")" | tr -d '\0')"

    return $ret
}
```

The `cygpath -w "$PWD"` call returns a Windows path; the differences:

```bash
$ echo "$PWD"
/d/Documents/Dev/Source/sonicretro/Sonic-Classic-Heroes

$ cygpath -w "$PWD"
D:\Documents\Dev\Source\sonicretro\Sonic-Classic-Heroes
```

Based on my limited understanding of Go, it seems that the code is failing to find the current directory the path contains slashes instead of backslashes, as evidenced by the tests with `-plain`.

**Comment by JanDeDobbeleer** [comment] 2021-12-13 22:03
Yes, but we're not going to use `--pwd="$(cygpath -w "$PWD")"` in a shared bash initialization. I'd rather remove the `--pwd` flag as that introduction causes this.

**Comment by lnu** [comment] 2021-12-14 06:51
the PWD was added to fix an issue that was not reproducible(#1207, but at least it was failing for the reporter). I'll give it a try when I'll reboot on macos.

**Comment by JanDeDobbeleer** [comment] 2021-12-14 08:47
@lnu we could also check for the presence of that command and use it to parse the path if it's there. Draft at #1430 (need to validate that)

**Comment by lnu** [comment] 2021-12-14 08:51
@JanDeDobbeleer yes but I don't really understand the initial issue because it works as expected with bash on macos without setting PWD. I don't see how the path could be persisted?

**Comment by flamewing** [comment] 2021-12-14 09:30
Note that the original reporter of #1207 also mentioned that they had something wrong during the setup. So maybe passing PWD was not at all connected to the issue being fixed on their end, and instead it went away when they fixed the setup. This hypothesis is supported by the fact that even the time was not updating on their first screenshot.

**Comment by flamewing** [comment] 2021-12-14 20:19
For what is worth, #1430 works on Windows on msys2 and Git bash, and on Ubuntu 21.10.

**Comment by JanDeDobbeleer** [comment] 2021-12-14 21:11
@flamewing merged, thanks for validating!

**Closed as completed** 2021-12-14 21:29 UTC
Labels: 🐛 bug
