### ISSUE TITLE
oh-my-posh fatal crash

### ISSUE THREAD

**Issue by coinzdude** [JanDeDobbeleer/oh-my-posh#2040] opened 2022-04-05 20:59 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Logging this bug by proxy...  Just an FYI in case it's interesting.  
Got a friend with a Windows VM, PS5 
OMP 7.59.0

![image](https://user-images.githubusercontent.com/58857646/161848551-51e99477-d3dc-4ac9-8ed5-3d71ce866124.png)
![image](https://user-images.githubusercontent.com/58857646/161848579-7694e39b-d4d6-4000-bed2-020af3b6bf8d.png)

I'll add any details I can get as well, like $profile settings, font use, etc.

```
oh-my-posh fatal error rendering session segment:runtime error: invalid memory address or nil pointer dereference

goroutine 20 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/debug/stack.go:24 +0x65
oh-my-posh/engine.(*Segment).renderText.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:326 +0x58
panic({0x820b40, 0x12d6900})
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:838 +0x207
strings.Count({0x0?, 0xc00005a120?}, {0x8ba548?, 0xc00002a060?})
        /opt/hostedtoolcache/go/1.18.0/x64/src/strings/strings.go:47 +0x50
strings.Replace({0x0, 0x17}, {0x8ba548, 0x1}, {0x8ba532, 0x1}, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.18.0/x64/src/strings/strings.go:1003 +0xcf
strings.ReplaceAll(...)
        /opt/hostedtoolcache/go/1.18.0/x64/src/strings/strings.go:1037
oh-my-posh/environment.DirMatchesOneOf({0x9f02f0, 0xc0001ee0e0}, {0x0?, 0xe?}, {0x1343d40, 0x0, 0x0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/shell.go:724 +0x76
oh-my-posh/engine.(*Segment).cwdExcluded(0xc0001b2640)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:209 +0xde
oh-my-posh/engine.(*Segment).shouldIncludeFolder(0xc0001b2640)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:182 +0x36
oh-my-posh/engine.(*Segment).renderText(0xc0001b2640, {0x9f02f0?, 0xc0001ee0e0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:332 +0x7b
oh-my-posh/engine.(*Block).renderSegmentsText.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:88 +0x65
created by oh-my-posh/engine.(*Block).renderSegmentsText
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:86 +0x98
```

### Theme

Set-PoshPrompt -Theme microverse-power

### What OS are you seeing the problem on?

Windows

### Which shell are you using?
Name                           Value
----                           -----
PSVersion                      5.1.20348.558
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.558
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Log output

```shell
oh-my-posh fatal error rendering session segment:runtime error: invalid memory address or nil pointer dereference

goroutine 20 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/debug/stack.go:24 +0x65
oh-my-posh/engine.(*Segment).renderText.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:326 +0x58
panic({0x820b40, 0x12d6900})
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:838 +0x207
strings.Count({0x0?, 0xc00005a120?}, {0x8ba548?, 0xc00002a060?})
        /opt/hostedtoolcache/go/1.18.0/x64/src/strings/strings.go:47 +0x50
strings.Replace({0x0, 0x17}, {0x8ba548, 0x1}, {0x8ba532, 0x1}, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.18.0/x64/src/strings/strings.go:1003 +0xcf
strings.ReplaceAll(...)
        /opt/hostedtoolcache/go/1.18.0/x64/src/strings/strings.go:1037
oh-my-posh/environment.DirMatchesOneOf({0x9f02f0, 0xc0001ee0e0}, {0x0?, 0xe?}, {0x1343d40, 0x0, 0x0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/shell.go:724 +0x76
oh-my-posh/engine.(*Segment).cwdExcluded(0xc0001b2640)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:209 +0xde
oh-my-posh/engine.(*Segment).shouldIncludeFolder(0xc0001b2640)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:182 +0x36
oh-my-posh/engine.(*Segment).renderText(0xc0001b2640, {0x9f02f0?, 0xc0001ee0e0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:332 +0x7b
oh-my-posh/engine.(*Block).renderSegmentsText.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:88 +0x65
created by oh-my-posh/engine.(*Block).renderSegmentsText
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:86 +0x98
```

**Comment by JanDeDobbeleer** [comment] 2022-04-05 21:08
@coinzdude duplicate of #2038 ;-)

**Closed as completed by JanDeDobbeleer** 2022-04-05 21:08 UTC
Labels: 👯‍♀️ duplicate

**Comment by coinzdude** [comment] 2022-04-05 22:31
closing!
