### ISSUE TITLE
Virus PUA:Win32/Caypnamer.A!ml detected

### ISSUE THREAD

**Issue by Marc013** [JanDeDobbeleer/oh-my-posh#1717] opened 2022-02-07 06:49 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Microsoft Defender Antivirus is reporting virus _PUA:Win32/Caypnamer.A!ml_ in executable oh-my-posh.exe.

![image](https://user-images.githubusercontent.com/28644241/152738279-0a140589-bec6-4a21-9559-bf244f9bd513.png)

### Theme

My own custom theme.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Version: 7.11.0

Segments:

ConsoleTitle(false) -   0 ms -
root(false)   -   0 ms -
exit(true)    -   0 ms - 
az(true)      -   1 ms -  ﴃ ********
az(true)      -   0 ms -  CLI 
path(true)    -   0 ms -  C:\
git(false)    -   4 ms -
python(false) -   0 ms -
exit(true)    -   0 ms - ❯

Run duration: 7.5012ms

Cache path: C:\Users\Marc********\AppData\Local/oh-my-posh

Logs:

2022/02/07 07:46:58 Args duration: 0s, args:
2022/02/07 07:46:58 Args duration: 0s, args:
2022/02/07 07:46:58 Args duration: 0s, args:
2022/02/07 07:46:58 Shell duration: 0s, args:
2022/02/07 07:46:58 debug: Getenv

2022/02/07 07:46:58 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 PathSeperator duration: 0s, args:
2022/02/07 07:46:58 PathSeperator duration: 0s, args:
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 Root duration: 0s, args:
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 ErrorCode duration: 0s, args:
2022/02/07 07:46:58 ErrorCode duration: 0s, args:
2022/02/07 07:46:58 Root duration: 0s, args:
2022/02/07 07:46:58 Shell duration: 0s, args:
2022/02/07 07:46:58 ErrorCode duration: 0s, args:
2022/02/07 07:46:58 IsWsl duration: 0s, args:
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 PathSeperator duration: 0s, args:
2022/02/07 07:46:58 PathSeperator duration: 0s, args:
2022/02/07 07:46:58 User duration: 0s, args:
2022/02/07 07:46:58 Host duration: 0s, args:
2022/02/07 07:46:58 GOOS duration: 0s, args:
2022/02/07 07:46:58 TemplateCache duration: 0s, args:
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 FileContent duration: 0s, args: C:\Users\Marc********\.azure\azureProfile.json
2022/02/07 07:46:58 TemplateCache duration: 0s, args:
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 FileContent duration: 0s, args: C:\Users\Marc********\.azure\azureProfile.json
2022/02/07 07:46:58 TemplateCache duration: 0s, args:
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 Args duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 GOOS duration: 0s, args:
2022/02/07 07:46:58 GOOS duration: 0s, args:
2022/02/07 07:46:58 PathSeperator duration: 0s, args:
2022/02/07 07:46:58 PathSeperator duration: 0s, args:
2022/02/07 07:46:58 PathSeperator duration: 0s, args:
2022/02/07 07:46:58 GOOS duration: 0s, args:
2022/02/07 07:46:58 IsWsl duration: 0s, args:
2022/02/07 07:46:58 StackCount duration: 0s, args:
2022/02/07 07:46:58 TemplateCache duration: 0s, args:
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 GOOS duration: 0s, args:
2022/02/07 07:46:58 HasCommand duration: 4.0493ms, args: git.exe
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/02/07 07:46:58 HasParentFilePath duration: 0s, args: .git
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 debug: Getenv

2022/02/07 07:46:58 Getenv duration: 0s, args: VIRTUAL_ENV
2022/02/07 07:46:58 debug: Getenv

2022/02/07 07:46:58 Getenv duration: 0s, args: CONDA_ENV_PATH
2022/02/07 07:46:58 debug: Getenv

2022/02/07 07:46:58 Getenv duration: 0s, args: CONDA_DEFAULT_ENV
2022/02/07 07:46:58 debug: Getenv

2022/02/07 07:46:58 Getenv duration: 0s, args: PYENV_VERSION
2022/02/07 07:46:58 debug: Pwd
C:\
2022/02/07 07:46:58 Pwd duration: 0s, args:
2022/02/07 07:46:58 debug: Home
C:\Users\Marc********
2022/02/07 07:46:58 ErrorCode duration: 0s, args:
2022/02/07 07:46:58 TemplateCache duration: 0s, args:
2022/02/07 07:46:58 debug: Getenv
C:\Users\Marc********\AppData\Local
2022/02/07 07:46:58 Getenv duration: 0s, args: LOCALAPPDATA
2022/02/07 07:46:58 CachePath duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment] 2022-02-07 06:51
@Marc013 false positive, duplicate of [this](https://github.com/JanDeDobbeleer/oh-my-posh/issues/767) issue.

**Closed as completed by JanDeDobbeleer** 2022-02-07 06:51 UTC
Labels: 🐛 bug

**Comment by Marc013** [comment] 2022-02-07 07:01
@JanDeDobbeleer,
Thank you for your quick response!

The reason of reporting this issue again is that since May 2021 I did not get this false positive anymore until this morning.
It looks like Microsoft has undone the previous fix to this issue in the latest update.

Just informing ;-)

**Comment by JanDeDobbeleer** [comment] 2022-02-07 07:03
@Marc013 I'll resubmit the binary.
