### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by tomgron** [JanDeDobbeleer/oh-my-posh#3256] opened 2022-12-27 16:41 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Oh-my-posh fails to initialize.

Output when trying to initialize oh-my-posh - updated with winget upgrade --all today 27.12.2022 to latest available version 12.31.0 :

```
PowerShell` 7.3.1
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x1?, 0x0?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xbf4106?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00015a300)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc00015a300)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/platform.(*Shell).Close(0xc00015a300)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:684 +0x87
oh-my-posh/cli.runInit({0xc000126080, 0x4})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/init.go:79 +0x2a5
oh-my-posh/cli.glob..func9(0x1f85b60?, {0xc0001c44e0?, 0x1?, 0x3?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/init.go:38 +0x3b
github.com/spf13/cobra.(*Command).execute(0x1f85b60, {0xc0001c4480, 0x3, 0x3})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f866e0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0x1579710?, 0xc000082000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x5?, 0x0?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xbf4106?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00024e840)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc00024e840)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/platform.(*Shell).Close(0xc00024e840)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:684 +0x87
oh-my-posh/cli.runInit({0xc0000360b0, 0x4})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/init.go:75 +0x23e
oh-my-posh/cli.glob..func9(0x1f85b60?, {0xc0002e2600?, 0x1?, 0x3?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/init.go:38 +0x3b
github.com/spf13/cobra.(*Command).execute(0x1f85b60, {0xc0002e25a0, 0x3, 0x3})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f866e0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0x1579710?, 0xc000082000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x5?, 0x7?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x0?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00009cb40)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc00009cb40)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/platform.(*Shell).Close(0xc00009cb40)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:684 +0x87
oh-my-posh/cli.glob..func10(0x1f86400?, {0xc0002b0870, 0x1?, 0x3?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/print.go:84 +0x5a3
github.com/spf13/cobra.(*Command).execute(0x1f86400, {0xc0002b0810, 0x3, 0x3})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f866e0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0x1579710?, 0xc000084000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
Loading personal and system profiles took 6584ms.
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc238f1?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x125e818?)
        /opt/hostedtoolcache/go/src/sync/waitgroup.go:139 +0x52
oh-my-posh/engine.(*Block).setEnabledSegments(0xc0001b6300)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:117 +0x187
oh-my-posh/engine.(*Block).executeSegmentLogic(0xc0001b6300)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:86 +0x7d
oh-my-posh/engine.(*Block).Init(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:64
oh-my-posh/engine.(*Engine).renderBlock(0xc000157f80, 0xc0001b6300)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:158 +0x196
oh-my-posh/engine.(*Engine).PrintPrimary(0xc000157f80)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:71 +0x45
oh-my-posh/cli.glob..func10(0x1f86400?, {0xc000292240, 0x1?, 0x9?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/print.go:68 +0x216
github.com/spf13/cobra.(*Command).execute(0x1f86400, {0xc0002921b0, 0x9, 0x9})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f866e0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0x1579710?, 0xc000084000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27

goroutine 19 [semacquire]:
sync.runtime_SemacquireMutex(0xc0003a4000?, 0xe0?, 0xc000389b80?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xc000394060?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00015aae0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/engine.(*Segment).cwdExcluded(0xc0001b8480)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:250 +0xab
oh-my-posh/engine.(*Segment).shouldIncludeFolder(0xc0001b8480)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:219 +0x36
oh-my-posh/engine.(*Segment).SetEnabled(0xc0001b8480, {0x158e638, 0xc00015aae0})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:392 +0x9e
oh-my-posh/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:114 +0x6a
created by oh-my-posh/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:112 +0x98

goroutine 20 [semacquire]:
sync.runtime_SemacquireMutex(0xc0003a40b0?, 0x80?, 0xc0003aa420?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xc000394180?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00015aae0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/engine.(*Segment).cwdExcluded(0xc0001b8600)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:250 +0xab
oh-my-posh/engine.(*Segment).shouldIncludeFolder(0xc0001b8600)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:219 +0x36
oh-my-posh/engine.(*Segment).SetEnabled(0xc0001b8600, {0x158e638, 0xc00015aae0})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:392 +0x9e
oh-my-posh/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:114 +0x6a
created by oh-my-posh/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:112 +0x98

goroutine 21 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x2?, 0x7?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xbf4106?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00015aae0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc00015aae0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/engine.(*Segment).SetEnabled(0xc0001b8780, {0x158e638, 0xc00015aae0})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:413 +0x252
oh-my-posh/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:114 +0x6a
created by oh-my-posh/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:112 +0x98
PS>
```

### Theme

M365Princess.omp.json

I init the theme by following line in my $PROFILE:

oh-my-posh init pwsh --config "C:\Users\TommiGrönlund\AppData\Local\Programs\oh-my-posh\themes\M365Princess.omp.json" | Invoke-Expression

(mind that my profile name DOES have 8-bit ascii letter ö)

### Log output

```Shell
PS>oh-my-posh debug
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x1?, 0x7?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xbf4106?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00013a0c0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc00013a0c0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/engine.(*Segment).SetEnabled(0xc00031e000, {0x158e638, 0xc00013a0c0})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:413 +0x252
oh-my-posh/engine.(*Block).Debug(0xc00031c000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:217 +0x145
oh-my-posh/engine.(*Engine).PrintDebug(0xc0000c7cc0, {0xc00013a0c0?, 0x0?, 0x1fad1e0?}, {0x1579710?, 0x0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:251 +0x658
oh-my-posh/cli.glob..func6(0x1f85e40?, {0x20029f8?, 0x0?, 0x0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/debug.go:56 +0x3b2
github.com/spf13/cobra.(*Command).execute(0x1f85e40, {0x20029f8, 0x0, 0x0})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f866e0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0x1579710?, 0xc000084000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc238f1?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x125e818?)
        /opt/hostedtoolcache/go/src/sync/waitgroup.go:139 +0x52
oh-my-posh/engine.(*Block).setEnabledSegments(0xc000304000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:117 +0x187
oh-my-posh/engine.(*Block).executeSegmentLogic(0xc000304000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:86 +0x7d
oh-my-posh/engine.(*Block).Init(...)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:64
oh-my-posh/engine.(*Engine).renderBlock(0xc000116780, 0xc000304000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:158 +0x196
oh-my-posh/engine.(*Engine).PrintPrimary(0xc000116780)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/engine.go:71 +0x45
oh-my-posh/cli.glob..func10(0x1f86400?, {0xc00013a120, 0x1?, 0x9?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/print.go:68 +0x216
github.com/spf13/cobra.(*Command).execute(0x1f86400, {0xc00013a090, 0x9, 0x9})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f866e0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
oh-my-posh/cli.Execute({0x1579710?, 0xc000084000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27

goroutine 18 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x0?, 0x7?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xbf4106?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).Pwd(0xc00013c060)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:334 +0xa5
oh-my-posh/platform.(*Shell).TemplateCache(0xc00013c060)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:736 +0x35b
oh-my-posh/engine.(*Segment).SetEnabled(0xc000306000, {0x158e638, 0xc00013c060})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:413 +0x252
oh-my-posh/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:114 +0x6a
created by oh-my-posh/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:112 +0x98

goroutine 19 [semacquire]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0xc000095db0?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x138e5e0?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).TemplateCache(0xc00013c060)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:711 +0x51
oh-my-posh/engine.(*Segment).SetEnabled(0xc000306180, {0x158e638, 0xc00013c060})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:413 +0x252
oh-my-posh/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:114 +0x6a
created by oh-my-posh/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:112 +0x98

goroutine 20 [semacquire]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0xc000325db0?)
        /opt/hostedtoolcache/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0x2002d80)
        /opt/hostedtoolcache/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x2?)
        /opt/hostedtoolcache/go/src/sync/rwmutex.go:147 +0x36
oh-my-posh/platform.(*Shell).TemplateCache(0xc00013c060)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:711 +0x51
oh-my-posh/engine.(*Segment).SetEnabled(0xc000306300, {0x158e638, 0xc00013c060})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:413 +0x252
oh-my-posh/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:114 +0x6a
created by oh-my-posh/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:112 +0x98
PS>
```

**Comment by brian-pickens** [comment] 2022-12-27 16:51
Also experiencing this error attempting to run the oh-my-posh init command.

**Comment by JanDeDobbeleer** [comment] 2022-12-27 16:58
duplicate of #3254, fix in [12.31.1](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v12.31.1)

For winget, either run the installer from the release (same result as winget), or wait for [this](https://github.com/microsoft/winget-pkgs/pull/92372) PR to get merged.

**Closed as completed by JanDeDobbeleer** 2022-12-27 16:58 UTC
Labels: 🐛 bug, 👯‍♀️ duplicate

**Comment by brian-pickens** [comment] 2022-12-27 17:00
Holy shit that was a fast turn around! I already updated. @JanDeDobbeleer :raised_hands:

**Comment by JanDeDobbeleer** [comment] 2022-12-27 17:02
@brian-pickens I have a very strict "You break it, you fix it" policy.

**Comment by guiireal** [comment] 2022-12-27 17:52
Hey brothers!

After updating oh-my-posh, the deadlocked issue is resolved, however when I run the command: 

`oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\paradox.omp.json" | Invoke-Expression`

In my Powershell profile $PROFILE when opening a new tab, the following error appears:



![image](https://user-images.githubusercontent.com/13739343/209703774-34f23f48-97ba-45f0-9f8c-bf8537216abc.png)

I don't know if it's because I'm using the `ç` character on my profile as "Guilherme França". In terminal showing: "Guilherme Fran├ºa/" in my user profile, the problem is that I have a lot of things installed and configured in this profile, undoing everything just to put oh-my-posh I don't know if it would be worth it. Is there any way to solve it?

**Comment by JanDeDobbeleer** [comment] 2022-12-27 17:58
@guiireal yes, PowerShell doesn't default to UTF8 so you'll need to temporarily set it on init. See [here](https://ohmyposh.dev/docs/faq#powershell-the-term-oh-my-poshexe-is-not-recognized-as-a-name-of-a-cmdlet) for more information.

**Comment by guiireal** [comment] 2022-12-27 18:04
> @guiireal yes, PowerShell doesn't default to UTF8 so you'll need to temporarily set it on init. See [here](https://ohmyposh.dev/docs/faq#powershell-the-term-oh-my-poshexe-is-not-recognized-as-a-name-of-a-cmdlet) for more information.

Great! Really my fault for not reading the FAQ, thanks for the solution!

**Comment by tomgron** [comment] 2022-12-28 04:47
Great, this got solved super fast. Brlliant work @JanDeDobbeleer - thanks for excellent tool.

**Comment by tomgron** [comment] 2022-12-28 04:48
> Hey brothers!
> 
> After updating oh-my-posh, the deadlocked issue is resolved, however when I run the command:
> 
> `oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\paradox.omp.json" | Invoke-Expression`
> 
> In my Powershell profile $PROFILE when opening a new tab, the following error appears:
> 
> ![image](https://user-images.githubusercontent.com/13739343/209703774-34f23f48-97ba-45f0-9f8c-bf8537216abc.png)
> 
> I don't know if it's because I'm using the `ç` character on my profile as "Guilherme França". In terminal showing: "Guilherme Fran├ºa/" in my user profile, the problem is that I have a lot of things installed and configured in this profile, undoing everything just to put oh-my-posh I don't know if it would be worth it. Is there any way to solve it?

Actually I got the same with my scandinavian letter ö in the name:

PowerShell 7.3.1
&: The term 'C:/Users/TommiGr├Ânlund/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.

Not related to this bug but rather annoying as this works on my desktop normally but not in my laptop 🤔

**Comment by JanDeDobbeleer** [comment] 2022-12-28 06:31
> @guiireal yes, PowerShell doesn't default to UTF8 so you'll need to temporarily set it on init. See [here](https://ohmyposh.dev/docs/faq#powershell-the-term-oh-my-poshexe-is-not-recognized-as-a-name-of-a-cmdlet) for more information.

@tomgron see the fix 👆🏻

**Comment by tomgron** [comment] 2022-12-29 18:35
> > @guiireal yes, PowerShell doesn't default to UTF8 so you'll need to temporarily set it on init. See [here](https://ohmyposh.dev/docs/faq#powershell-the-term-oh-my-poshexe-is-not-recognized-as-a-name-of-a-cmdlet) for more information.
> 
> @tomgron see the fix 👆🏻

I tried that fix and it surely fixes oh-my-posh but breaks Jetbrains Toolbox and some other java -based apps that doesn't support that solution unfortunately so I can't turn that UTF-8 on for productivity reasons.

**Comment by JanDeDobbeleer** [comment] 2022-12-29 18:37
@tomgron the fix only sets the shell to UTF8 for initializing oh-my-posh then sets it back to whatever it was before. So it _should_ not break anything else.

**Comment by tomgron** [comment] 2022-12-29 20:15
> 

Oh, sorry, I though you meant this : 
![image](https://user-images.githubusercontent.com/1743381/210007007-667030f5-d01e-4f6b-bac7-1895d5194493.png)

I'll try that out

**Comment by tomgron** [comment] 2022-12-29 20:17
> @tomgron the fix only sets the shell to UTF8 for initializing oh-my-posh then sets it back to whatever it was before. So it _should_ not break anything else.

That worked perfectly, thanks
