### ISSUE TITLE
Once terraform segment is enabled, exit codes are no longer reported

### ISSUE THREAD

**Issue by glucas** [JanDeDobbeleer/oh-my-posh#388] opened 2021-02-08 13:58 UTC
I have a theme that includes the exit status of the last command (shown for non-zero exit codes) as well as the terraform workspace (which shows only when in an appropriate directory).

The exit segment works as expected until the first time I cd in to a terraform directory. From then on the exit segment no longer shows me failed commands, regardless of the current directory. If I start a new shell the behavior repeats, i.e. works fine until I go to a terraform directory.

Perhaps the terraform segment is adding some command that stomps on the last exit code? I haven't tried to debug further yet.

**Comment by JanDeDobbeleer** [comment] 2021-02-08 17:09
The exitcode is handles before running the prompt

**Comment by JanDeDobbeleer** [comment] 2021-02-08 17:10
The exit code is added before running a command meaning it can't be influenced by anything (unless that segment messes with it). I'll check .

**Comment by JanDeDobbeleer** [comment] 2021-02-10 14:29
@glucas would you mind using the issue template so I can get some info in your system? I need to reproduce this and the source of where we get the exit code before rendering the prompt differs based on the shell/invocation. Thanks.

**Comment by glucas** [comment] 2021-02-11 19:56
I've updated to the latest oh-my-posh3 (via scoop) with the intent of providing a more detailed test case... and now things appear to be working. 

I'm not sure if something changed in 3.85 or if was a change somewhere else in my shell environment, but now it works as expected. Sorry for the noise! 


### Environment

- Oh my Posh version:   oh-my-posh3: 3.85.0
- Theme: Custom, started from slim
- Operating System: Windows 10 (1909)
- Shell: pwsh (PSVersion 7.1.1)
- Terminal: Windows Terminal (1.5.210127001-release1.5)

**Comment by JanDeDobbeleer** [comment] 2021-02-11 20:05
@glucas no worries, thanks for reporting back! I'll close it as it was the only case, I couldn't reproduce it on my end either.

**Closed as completed** 2021-02-11 20:05 UTC
Labels: 🐛 bug
