### ISSUE TITLE
Git segment should have timeout or better optimization

### ISSUE THREAD

**Issue by Weilbyte** [JanDeDobbeleer/oh-my-posh#308] opened 2021-01-03 02:12 UTC
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The Git segment should have a timeout setting, as entering a large git repository is going to block the terminal a lot. The repository I cloned is https://github.com/MinecraftForge/MCPConfig (with a depth of 1). Attempting to enter the folder regardless if done from Windows or WSL2 will take a long time.

After removing the `.git` folder and re-entering the folder, the delay was gone.

### Environment

- Oh my Posh version: `3.66.3`
- Theme: Custom (https://gist.github.com/Weilbyte/b7060ed1fa9b9608b9c93eb5ddf5a35b)
- Operating System: Windows 10 Pro
- Shell: powershell/zsh/bash
- Terminal: Windows Terminal

### Steps to Reproduce

1. Clone big git repository (as an example, use the one in my issue description)
2. `cd <directory>`

**Expected behavior:** 
To enter the directory sub-1s.

**Actual behavior:**
Directory entered after huge delay.

**Comment by JanDeDobbeleer** [comment] 2021-01-03 07:02
Duplicate of #305

**Closed as completed by JanDeDobbeleer** 2021-01-03 07:02 UTC
