### ISSUE TITLE
Terminal does not wrap correctly on Debian 11

### ISSUE THREAD

**Issue by CJCombrink** [JanDeDobbeleer/oh-my-posh#2611] opened 2022-08-04 10:22 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When typing in the prompt, if the end of the line is reached the prompt wraps to the start of the current line and not creating a new line underneath. 

Also happens when going back in history for such long lines (pressing up arrow)

### Theme

Default and "paradox.omp.json" tested

Complete setup:
Terminal: Windows Terminal Preview
SSH to Centos Host OS
Bash with OMP installed in Docker container: Debian 11

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
oh-my-posh debug                                                        in bash at 10:12

Version: 8.26.1

Segments:

ConsoleTitle(true) -  14 ms - bash in /
session(false) -   0 ms -
path(true)     -   0 ms -   /
git(false)     -   0 ms -
root(true)     -   0 ms -  
exit(true)     -   0 ms -   
node(false)    -   0 ms -
go(false)      -   0 ms -
python(false)  -   0 ms -
shell(true)    -   0 ms - in bash
time(true)     -   0 ms - at 10:12:57

Run duration: 46.035913ms

Cache path: /root

Config path: /root/config.omp.json

Logs:

2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 7.749µs, args: XDG_CACHE_HOME
2022/08/04 10:12:57 CachePath duration: 20.784µs, args:
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 2.188µs, args: POSH_THEME
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 705ns, args: XDG_CACHE_HOME
2022/08/04 10:12:57 CachePath duration: 4.121µs, args:
2022/08/04 10:12:57 debug: HTTPRequest
GET /JanDeDobbeleer/oh-my-posh/v8.26.1/themes/default.omp.json HTTP/1.1
Host: raw.githubusercontent.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/08/04 10:12:57 debug: HTTPRequest
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "p:yellow",
          "foreground": "p:black",
          "leading_diamond": "\ue0b6",
          "properties": {
            "display_host": false
          },
          "style": "diamond",
          "template": " {{ if .SSHSession }}\uf817 {{ end }}{{ .UserName }} ",
          "trailing_diamond": "\ue0b0",
          "type": "session"
        },
        {
          "background": "p:orange",
          "foreground": "p:white",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "home_icon": "~",
            "style": "folder"
          },
          "style": "powerline",
          "template": " \uf74a {{ path .Path .Location }} ",
          "type": "path"
        },
        {
          "background": "p:green",
          "background_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
            "{{ if gt .Ahead 0 }}#49416D{{ end }}",
            "{{ if gt .Behind 0 }}#7A306C{{ end }}"
          ],
          "foreground": "p:black",
          "foreground_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}",
            "{{ if gt .Ahead 0 }}p:white{{ end }}"
          ],
          "powerline_symbol": "\ue0b0",
          "properties": {
            "branch_max_length": 25,
            "fetch_status": true,
            "fetch_upstream_icon": true,
            "github_icon": "\uf7a3"
          },
          "style": "powerline",
          "template": " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} ",
          "type": "git"
        },
        {
          "background": "p:yellow",
          "foreground": "p:white",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "root_icon": "\uf0ad"
          },
          "style": "powerline",
          "template": " \uf0e7 ",
          "type": "root"
        },
        {
          "background": "p:blue",
          "background_templates": [
            "{{ if gt .Code 0 }}p:red{{ end }}"
          ],
          "foreground": "p:white",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "properties": {
            "always_enabled": true
          },
          "style": "diamond",
          "template": " {{ if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }} ",
          "trailing_diamond": "\ue0b4",
          "type": "exit"
        }
      ],
      "type": "prompt"
    },
    {
      "segments": [
        {
          "background": "transparent",
          "foreground": "p:green",
          "properties": {
            "display_mode": "files",
            "fetch_package_manager": false,
            "home_enabled": false
          },
          "style": "plain",
          "template": "\uf898 ",
          "type": "node"
        },
        {
          "background": "transparent",
          "foreground": "p:blue",
          "properties": {
            "fetch_version": false
          },
          "style": "powerline",
          "template": "\ufcd1 ",
          "type": "go"
        },
        {
          "background": "transparent",
          "foreground": "p:yellow",
          "properties": {
            "display_mode": "files",
            "fetch_version": true,
            "fetch_virtual_env": false
          },
          "style": "plain",
          "template": "\ue235 ",
          "type": "python"
        },
        {
          "background": "transparent",
          "foreground": "p:white",
          "style": "plain",
          "template": "in <p:blue><b>{{ .Name }}</b></> ",
          "type": "shell"
        },
        {
          "background": "transparent",
          "foreground": "p:white",
          "style": "plain",
          "template": "at <p:blue><b>{{ .CurrentDate | date \"15:04:05\" }}</b></>",
          "type": "time"
        }
      ],
      "type": "rprompt"
    }
  ],
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true,
  "palette": {
    "black": "#262B44",
    "blue": "#4B95E9",
    "green": "#59C9A5",
    "orange": "#F07623",
    "red": "#D81E5B",
    "white": "#E0DEF4",
    "yellow": "#F3AE35"
  },
  "secondary_prompt": {
    "background": "transparent",
    "foreground": "p:black",
    "template": "<p:yellow,transparent>\ue0b6</><,p:yellow> > </><p:yellow,transparent>\ue0b0</> "
  },
  "tooltips": [
    {
      "background": "p:orange",
      "foreground": "p:white",
      "leading_diamond": "\ue0b6",
      "properties": {
        "display_default": true
      },
      "style": "diamond",
      "template": " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} ",
      "tips": [
        "aws"
      ],
      "trailing_diamond": "\ue0b4",
      "type": "aws"
    },
    {
      "background": "p:blue",
      "foreground": "p:white",
      "leading_diamond": "\ue0b6",
      "style": "diamond",
      "template": " \ufd03 {{ .Name }} ",
      "tips": [
        "az"
      ],
      "trailing_diamond": "\ue0b4",
      "type": "az"
    }
  ],
  "transient_prompt": {
    "background": "transparent",
    "foreground": "p:black",
    "template": "<p:yellow,transparent>\ue0b6</><,p:yellow> {{ .Folder }} </><p:yellow,transparent>\ue0b0</> "
  },
  "version": 2
}

2022/08/04 10:12:57 HTTPRequest duration: 27.97703ms, args: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v8.26.1/themes/default.omp.json
2022/08/04 10:12:57 downloadConfig duration: 28.089652ms, args: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v8.26.1/themes/default.omp.json
2022/08/04 10:12:57 resolveConfigPath duration: 28.100023ms, args:
2022/08/04 10:12:57 Init duration: 28.945965ms, args:
2022/08/04 10:12:57 Flags duration: 46ns, args:
2022/08/04 10:12:57 config.loadConfig duration: 507.414µs, args:
2022/08/04 10:12:57 Flags duration: 46ns, args:
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 1.474µs, args: OMP_CACHE_DISABLED
2022/08/04 10:12:57 Root duration: 459ns, args:
2022/08/04 10:12:57 Shell duration: 13.668813ms, args:
2022/08/04 10:12:57 ErrorCode duration: 140ns, args:
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 1.241µs, args: WSL_DISTRO_NAME
2022/08/04 10:12:57 IsWsl duration: 3.175µs, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 10.371µs, args:
2022/08/04 10:12:57 debug: User

2022/08/04 10:12:57 User duration: 830ns, args:
2022/08/04 10:12:57 debug: Host
961816f47131
2022/08/04 10:12:57 Host duration: 1.783µs, args:
2022/08/04 10:12:57 GOOS duration: 40ns, args:
2022/08/04 10:12:57 TemplateCache duration: 13.708082ms, args:
2022/08/04 10:12:57 Flags duration: 52ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 878ns, args:
2022/08/04 10:12:57 GOOS duration: 30ns, args:
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 935ns, args: SSH_CONNECTION
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 763ns, args: SSH_CLIENT
2022/08/04 10:12:57 TemplateCache duration: 56ns, args:
2022/08/04 10:12:57 TemplateCache duration: 77ns, args:
2022/08/04 10:12:57 Shell duration: 103ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 893ns, args:
2022/08/04 10:12:57 GOOS duration: 44ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 612ns, args:
2022/08/04 10:12:57 Flags duration: 53ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 667ns, args:
2022/08/04 10:12:57 GOOS duration: 25ns, args:
2022/08/04 10:12:57 GOOS duration: 26ns, args:
2022/08/04 10:12:57 PathSeparator duration: 45ns, args:
2022/08/04 10:12:57 GOOS duration: 27ns, args:
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 763ns, args: WSL_DISTRO_NAME
2022/08/04 10:12:57 IsWsl duration: 1.839µs, args:
2022/08/04 10:12:57 StackCount duration: 53ns, args:
2022/08/04 10:12:57 DirIsWritable duration: 3.045µs, args:
2022/08/04 10:12:57 TemplateCache duration: 30ns, args:
2022/08/04 10:12:57 TemplateCache duration: 100ns, args:
2022/08/04 10:12:57 Shell duration: 31ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 1.02µs, args:
2022/08/04 10:12:57 GOOS duration: 36ns, args:
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 748ns, args: WSL_DISTRO_NAME
2022/08/04 10:12:57 IsWsl duration: 3.615µs, args:
2022/08/04 10:12:57 GOOS duration: 28ns, args:
2022/08/04 10:12:57 error: CommandPath
not relevant
2022/08/04 10:12:57 CommandPath duration: 17.594µs, args: git
2022/08/04 10:12:57 HasCommand duration: 18.935µs, args: git
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 805ns, args:
2022/08/04 10:12:57 GOOS duration: 30ns, args:
2022/08/04 10:12:57 Root duration: 268ns, args:
2022/08/04 10:12:57 TemplateCache duration: 27ns, args:
2022/08/04 10:12:57 TemplateCache duration: 32ns, args:
2022/08/04 10:12:57 Shell duration: 29ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 762ns, args:
2022/08/04 10:12:57 GOOS duration: 48ns, args:
2022/08/04 10:12:57 ErrorCode duration: 45ns, args:
2022/08/04 10:12:57 TemplateCache duration: 29ns, args:
2022/08/04 10:12:57 TemplateCache duration: 73ns, args:
2022/08/04 10:12:57 Shell duration: 54ns, args:
2022/08/04 10:12:57 TemplateCache duration: 53ns, args:
2022/08/04 10:12:57 Flags duration: 76ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 814ns, args:
2022/08/04 10:12:57 GOOS duration: 32ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 814ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 603ns, args:
2022/08/04 10:12:57 PathSeparator duration: 42ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 56.439µs, args: *.js
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 748ns, args:
2022/08/04 10:12:57 PathSeparator duration: 25ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 23.003µs, args: *.ts
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 660ns, args:
2022/08/04 10:12:57 PathSeparator duration: 25ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 4.624µs, args: package.json
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 572ns, args:
2022/08/04 10:12:57 PathSeparator duration: 26ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 3.79µs, args: .nvmrc
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 597ns, args:
2022/08/04 10:12:57 PathSeparator duration: 28ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 4.155µs, args: pnpm-workspace.yaml
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 592ns, args:
2022/08/04 10:12:57 PathSeparator duration: 26ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 3.791µs, args: .pnpmfile.cjs
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 568ns, args:
2022/08/04 10:12:57 PathSeparator duration: 27ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 5.676µs, args: .npmrc
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 559ns, args:
2022/08/04 10:12:57 PathSeparator duration: 26ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 3.62µs, args: .vue
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 736ns, args:
2022/08/04 10:12:57 GOOS duration: 34ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 633ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 630ns, args:
2022/08/04 10:12:57 PathSeparator duration: 25ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 22.513µs, args: *.go
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 751ns, args:
2022/08/04 10:12:57 PathSeparator duration: 25ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 4.703µs, args: go.mod
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 702ns, args:
2022/08/04 10:12:57 GOOS duration: 44ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 634ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 652ns, args:
2022/08/04 10:12:57 PathSeparator duration: 24ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 22.255µs, args: *.py
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 654ns, args:
2022/08/04 10:12:57 PathSeparator duration: 26ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 21.295µs, args: *.ipynb
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 602ns, args:
2022/08/04 10:12:57 PathSeparator duration: 25ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 3.876µs, args: pyproject.toml
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 545ns, args:
2022/08/04 10:12:57 PathSeparator duration: 26ns, args:
2022/08/04 10:12:57 debug: HasFiles
false
2022/08/04 10:12:57 HasFiles duration: 4.41µs, args: venv.bak
2022/08/04 10:12:57 debug: HasFolder
false
2022/08/04 10:12:57 HasFolder duration: 1.997µs, args: .venv
2022/08/04 10:12:57 debug: HasFolder
false
2022/08/04 10:12:57 HasFolder duration: 1.422µs, args: venv
2022/08/04 10:12:57 debug: HasFolder
false
2022/08/04 10:12:57 HasFolder duration: 1.515µs, args: virtualenv
2022/08/04 10:12:57 debug: HasFolder
false
2022/08/04 10:12:57 HasFolder duration: 1.448µs, args: env
2022/08/04 10:12:57 debug: HasFolder
false
2022/08/04 10:12:57 HasFolder duration: 1.745µs, args: venv-win
2022/08/04 10:12:57 debug: HasFolder
false
2022/08/04 10:12:57 HasFolder duration: 1.545µs, args: pyenv-win
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 759ns, args:
2022/08/04 10:12:57 GOOS duration: 30ns, args:
2022/08/04 10:12:57 Shell duration: 39ns, args:
2022/08/04 10:12:57 Flags duration: 70ns, args:
2022/08/04 10:12:57 TemplateCache duration: 26ns, args:
2022/08/04 10:12:57 TemplateCache duration: 32ns, args:
2022/08/04 10:12:57 Shell duration: 51ns, args:
2022/08/04 10:12:57 debug: Pwd
/
2022/08/04 10:12:57 Pwd duration: 918ns, args:
2022/08/04 10:12:57 GOOS duration: 35ns, args:
2022/08/04 10:12:57 TemplateCache duration: 27ns, args:
2022/08/04 10:12:57 TemplateCache duration: 281ns, args:
2022/08/04 10:12:57 Shell duration: 141ns, args:
2022/08/04 10:12:57 debug: Getenv

2022/08/04 10:12:57 Getenv duration: 1.403µs, args: XDG_CACHE_HOME
2022/08/04 10:12:57 CachePath duration: 8.005µs, args:
2022/08/04 10:12:57 Flags duration: 42ns, args:
```

**Comment by JanDeDobbeleer** [comment] 2022-08-04 10:25
This is for bash right? I'll check of there's something which isn't escaped properly.

**Comment by CJCombrink** [comment] 2022-08-04 10:27
Yes bash

**Comment by CJCombrink** [comment] 2022-08-04 10:29
Steps to reproduce using Docker
```
docker run --rm -it debian:11
apt update
apt install -y sudo wget unzip
# Steps from Installation page
sudo wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
sudo chmod +x /usr/local/bin/oh-my-posh
mkdir ~/.poshthemes
wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip -O ~/.poshthemes/themes.zip
unzip ~/.poshthemes/themes.zip -d ~/.poshthemes
chmod u+rw ~/.poshthemes/*.omp.*
rm ~/.poshthemes/themes.zip
# Enable
echo 'eval "$(oh-my-posh init bash)"' | tee -a ~/.bashrc
exec bash
```

**Comment by JanDeDobbeleer** [comment] 2022-08-04 10:47
@CJCombrink for what it's worth, I can't reproduce this on macOS running `GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.6.0)`, will try the container next.

**Comment by JanDeDobbeleer** [comment] 2022-08-04 10:58
@CJCombrink I can reproduce the bug inside the container. That does mean, that version of bash has an issue which 5.1.16 doesn't have AND I know they fixed severe bugs in past years on that topic (that version is 2 years old). I'll try to update, but maybe you can give that a go as well on your end.

**Comment by CJCombrink** [comment] 2022-08-04 11:04
Another interesting finding is that it works in centos8-stream container as well
Steps as before but to start of with
```
docker run --rm -it quay.io/centos/centos:stream8
dnf update 
dnf install -y sudo wget unzip
```
The bash in the centos container is: `GNU bash, version 4.4.20(1)-release`

Edit: Just to be clear, it works *correctly* in the centos container

**Comment by JanDeDobbeleer** [comment] 2022-08-04 11:59
@CJCombrink yup, that's an older stable version. So my assumption is that the 5.1.4 version is wonky. I'll try to find a way to update it, but that's probably going to be a manual process as it's been an open issue on Debian for half a year now...

**Comment by CJCombrink** [comment] 2022-08-04 12:02
@JanDeDobbeleer Ok I will also try to update my bash (could not find an easy answer yet except for manual rebuild)
If that is the case (due to bug in bash 5.1.4) then I am happy to close this ticket as "not your problem/fault".

Will try to test as soon as I can and revert back

**Comment by CJCombrink** [comment] 2022-08-04 12:53
I did install a newer version of bash using brew but the behaviour is still broken. 
Different compared to the original issue, but still broken

Not sure if the brew route was a good idea though.

**Comment by JanDeDobbeleer** [comment] 2022-08-04 13:35
@CJCombrink this still somehow is an issue outside of the scope of oh-my-posh as I can't reproduce this on the same version on macOS, nor any other. When this happens, it implies that the character escaping is wrong, which is an oh-my-posh issue. However, it can't be that this is different on 1 system vs the other as that's a bash and oh-my-posh combo problem (we provide the output, bash parses it and readline interpretes it) and very reproducible using the same version of bash and oh-my-posh. So I'm puzzled, even when I can reproduce it, it makes zero sense. It even happens on super simple prompts such as agnoster, which have almost no special cases in there.

**Comment by JanDeDobbeleer** [comment] 2022-08-04 13:55
@CJCombrink in my container, it even does this without oh-my-posh, line wrapping is just off in the Debian container... This isn't an oh-my-posh, I'm closing the ticket and will try to find out what's causing that out of curiosity.

**Closed as completed by JanDeDobbeleer** 2022-08-04 13:55 UTC
Labels: 🐛 bug

**Comment by CJCombrink** [comment] 2022-08-05 07:23
I tend to agree, it is container issue
I did a quick test on a Debian WSL install and it also works fine there.

**Comment by JanDeDobbeleer** [comment] 2022-08-05 07:32
@CJCombrink I could find a lot of issues describing the same, and all related to docker not taking into account the terminal size. So a search in that direction might be worthwhile.
