### ISSUE TITLE
Python segment: when should it appear?

### ISSUE THREAD

**Issue by meakbiyik** [JanDeDobbeleer/oh-my-posh#240] opened 2020-12-14 21:45 UTC
This will be a slightly vague feature request, but I am not very comfortable with the current state so here it goes.

As is, python segment only appears when there is a .py or .ipynb file in the cwd. However, there are multiple cases for me that this is insufficient:

1. When I want to start jupyter, or just do some basic scripting by opening the cmd, I would like to know at least which python I am using, e.g base conda or some other conda?
2. When I am writing a package, I always use an environment in the root location (a PEP-compliant dependency management tool called poetry creates this in the root location of the package using virtualenv, with the folder name .venv). I never, or at least very rarely go down inside the module, I just run the package as a module from the upper level, and vscode does to activation of the environment automatically so I do not need to do anything else. The existence of "pyproject.toml" file is a good indicator that the directory is a python package, if such a thing is needed.

Can there be at least a flag to cover these use cases? I do not know if some cleverness is needed, or just allowing the environment name to appear all the time with an optional boolean is enough. Just that the current state does not exactly work.

Thanks in advance!

**Comment by JanDeDobbeleer** [comment] 2020-12-15 06:10
@meakbiyik this is almost a duplicate of #239, can you check and add this context there? That way we can come up with 1 way to cover these cases 🙏🏻

**Closed as completed** 2020-12-15 06:10 UTC
Labels: 👯‍♀️ duplicate
