### ISSUE TITLE
SentinelOne detects oh-my-posh.exe as a virus

### ISSUE THREAD

**Issue by achiyae** [JanDeDobbeleer/oh-my-posh#792] opened 2021-06-08 11:36 UTC
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [ ] I looked for duplicate issues before submitting this one

### Description

I have SentinelOne 21.5.3.235 anti-virus from my workplace and whenever I try to install oh-my-posh on my machine (install file/pwsh/winget) - SentinelOne detects the exe file as malware and deletes it.

### Environment

- Oh My Posh version: all latest versions. 
- Theme: N/A
- Operating System: Windows
- Shell: not-relevant
- Terminal: not-relevant

**Comment by JanDeDobbeleer** [comment] 2021-06-08 11:52
@eggsterino this is a duplicate of https://github.com/JanDeDobbeleer/oh-my-posh/issues/767

**Closed as completed by JanDeDobbeleer** 2021-06-08 11:52 UTC
