### ISSUE TITLE
Strange init script on Alpine Linux

### ISSUE THREAD

**Issue by DrMagPie** [JanDeDobbeleer/oh-my-posh#1335] opened 2021-11-27 12:54 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi,

For some reason latest version is producing broken init script.

here is what it is producing
```fish
set -g POSH_THEME ""
set -g POWERLINE_COMMAND "oh-my-posh"
set -g CONDA_PROMPT_MODIFIER false

function fish_prompt
    set omp_status_cache $status
    set omp_stack_count (count $dirstack)
    set omp_duration "$CMD_DURATION$cmd_duration"
    # check if variable set, < 3.2 case
    if set -q omp_lastcommand; and test "$omp_lastcommand" = ""
      set omp_duration 0
    end
    # works with fish >=3.2
    if set -q omp_last_status_generation; and test "$omp_last_status_generation" = "$status_generation"
      set omp_duration 0
    end
    if set -q status_generation
      set -gx omp_last_status_generation $status_generation
    end

    /lib/ld-musl-x86_64.so.1 --config $POSH_THEME --error $omp_status_cache --execution-time $omp_duration --stack-count $omp_stack_count
end

function postexec_omp --on-event fish_postexec
  # works with fish <3.2
  # pre and postexec not fired for empty command in fish >=3.2
  set -gx omp_lastcommand $argv
end


function export_poshconfig
  set -l file_name $argv[1]
  set -l format $argv[2]
  if not test -n "$file_name"
    echo "Usage: export_poshconfig \"filename\""
    return
  end
  if not test -n "$format"
    set format "json"
  end
  /lib/ld-musl-x86_64.so.1 --config $POSH_THEME --print-config --config-format $format > $file_name
end
```

and if sourced it results in following error
```shell
 oh-my-posh --init --shell fish | source
musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname [args]
```

I think that before there was `oh-my-posh` instead of `/lib/ld-musl-x86_64.so.1` 
So I have manually replaced it in init script and sourced edited version instead of generated by this command `oh-my-posh --init --shell fish` 
It helped and prompt is working for me.

Manually edited init script:
```fish
set -g POSH_THEME ""
set -g POWERLINE_COMMAND "oh-my-posh"
set -g CONDA_PROMPT_MODIFIER false

function fish_prompt
    set omp_status_cache $status
    set omp_stack_count (count $dirstack)
    set omp_duration "$CMD_DURATION$cmd_duration"
    # check if variable set, < 3.2 case
    if set -q omp_lastcommand; and test "$omp_lastcommand" = ""
      set omp_duration 0
    end
    # works with fish >=3.2
    if set -q omp_last_status_generation; and test "$omp_last_status_generation" = "$status_generation"
      set omp_duration 0
    end
    if set -q status_generation
      set -gx omp_last_status_generation $status_generation
    end

    oh-my-posh --config $POSH_THEME --error $omp_status_cache --execution-time $omp_duration --stack-count $omp_stack_count
end

function postexec_omp --on-event fish_postexec
  # works with fish <3.2
  # pre and postexec not fired for empty command in fish >=3.2
  set -gx omp_lastcommand $argv
end


function export_poshconfig
  set -l file_name $argv[1]
  set -l format $argv[2]
  if not test -n "$file_name"
    echo "Usage: export_poshconfig \"filename\""
    return
  end
  if not test -n "$format"
    set format "json"
  end
  oh-my-posh --config $POSH_THEME --print-config --config-format $format > $file_name
end
```

I also tried to use bash, and above described behavior persisted.
Could you please investigate it.

### Theme

Any

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

fish

### Log output

```shell
Version: 6.16.0

Segments:

ConsoleTitle(true) -   0 ms -
session(true)  -   0 ms -  user@HOST 
path(true)     -   0 ms -   ~ 
git(false)     -   0 ms -
battery(true)  -   0 ms -  100 
node(false)    -   0 ms -
shell(true)    -   0 ms -  ﲵ fish 
root(false)    -   0 ms -
text(true)     -   0 ms -  NO CONFIG 
exit(true)     -   0 ms -   

Run duration: 1.1712ms

Logs:

2021/11/27 12:33:31 debug: getenv

2021/11/27 12:33:31 getenv duration: 4.2µs, args: XDG_CACHE_HOME
2021/11/27 12:33:31 getCachePath duration: 13.7µs, args:
2021/11/27 12:33:31 getArgs duration: 100ns, args:
2021/11/27 12:33:31 getArgs duration: 0s, args:
2021/11/27 12:33:31 getShellName duration: 100ns, args:
2021/11/27 12:33:31 debug: getenv

2021/11/27 12:33:31 getenv duration: 1.2µs, args: OMP_CACHE_DISABLED
2021/11/27 12:33:31 isRunningAsRoot duration: 300ns, args:
2021/11/27 12:33:31 getcwd duration: 16.4µs, args:
2021/11/27 12:33:31 getPathSeperator duration: 100ns, args:
2021/11/27 12:33:31 getPathSeperator duration: 100ns, args:
2021/11/27 12:33:31 getShellName duration: 100ns, args:
2021/11/27 12:33:31 getCurrentUser duration: 100ns, args:
2021/11/27 12:33:31 getHostName duration: 1.3µs, args:
2021/11/27 12:33:31 getcwd duration: 100ns, args:
2021/11/27 12:33:31 getCurrentUser duration: 100ns, args:
2021/11/27 12:33:31 getRuntimeGOOS duration: 100ns, args:
2021/11/27 12:33:31 getHostName duration: 800ns, args:
2021/11/27 12:33:31 debug: getenv

2021/11/27 12:33:31 getenv duration: 1µs, args: SSH_CONNECTION
2021/11/27 12:33:31 debug: getenv

2021/11/27 12:33:31 getenv duration: 600ns, args: SSH_CLIENT
2021/11/27 12:33:31 debug: getenv

2021/11/27 12:33:31 getenv duration: 600ns, args: POSH_SESSION_DEFAULT_USER
2021/11/27 12:33:31 getcwd duration: 100ns, args:
2021/11/27 12:33:31 getcwd duration: 100ns, args:
2021/11/27 12:33:31 getArgs duration: 100ns, args:
2021/11/27 12:33:31 getcwd duration: 0s, args:
2021/11/27 12:33:31 getRuntimeGOOS duration: 0s, args:
2021/11/27 12:33:31 getRuntimeGOOS duration: 0s, args:
2021/11/27 12:33:31 getPathSeperator duration: 0s, args:
2021/11/27 12:33:31 getPathSeperator duration: 0s, args:
2021/11/27 12:33:31 getPathSeperator duration: 0s, args:
2021/11/27 12:33:31 getRuntimeGOOS duration: 0s, args:
2021/11/27 12:33:31 getcwd duration: 0s, args:
2021/11/27 12:33:31 getRuntimeGOOS duration: 100ns, args:
2021/11/27 12:33:31 debug: getenv
Alpine
2021/11/27 12:33:31 getenv duration: 800ns, args: WSL_DISTRO_NAME
2021/11/27 12:33:31 isWsl duration: 2µs, args:
2021/11/27 12:33:31 getcwd duration: 0s, args:
2021/11/27 12:33:31 hasCommand duration: 7.5µs, args: git
2021/11/27 12:33:31 getcwd duration: 0s, args:
2021/11/27 12:33:31 error: hasParentFilePath
stat /.git: no such file or directory
2021/11/27 12:33:31 hasParentFilePath duration: 9.4µs, args: .git
2021/11/27 12:33:31 getcwd duration: 0s, args:
2021/11/27 12:33:31 getBatteryInfo duration: 346.1µs, args:
2021/11/27 12:33:31 getcwd duration: 200ns, args:
2021/11/27 12:33:31 getcwd duration: 0s, args:
2021/11/27 12:33:31 getcwd duration: 100ns, args:
2021/11/27 12:33:31 getShellName duration: 100ns, args:
2021/11/27 12:33:31 getcwd duration: 100ns, args:
2021/11/27 12:33:31 isRunningAsRoot duration: 300ns, args:
2021/11/27 12:33:31 getcwd duration: 100ns, args:
2021/11/27 12:33:31 isRunningAsRoot duration: 100ns, args:
2021/11/27 12:33:31 getcwd duration: 100ns, args:
2021/11/27 12:33:31 getPathSeperator duration: 100ns, args:
2021/11/27 12:33:31 getPathSeperator duration: 100ns, args:
2021/11/27 12:33:31 getShellName duration: 0s, args:
2021/11/27 12:33:31 getCurrentUser duration: 200ns, args:
2021/11/27 12:33:31 getHostName duration: 700ns, args:
2021/11/27 12:33:31 getcwd duration: 200ns, args:
2021/11/27 12:33:31 lastErrorCode duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment] 2021-11-27 13:15
@DrMagPie that's weird. We get the name of the running executable from go, so that's reporting the wrong info in that case.

**Comment by DrMagPie** [comment] 2021-11-27 13:30
Hmmm....
Then I can only guess, that Alpine is doing some strange magic with processes.
Or it is a bug within the Go...

Interesting bit is that it was working fine on a previous PC. But unfortunately I don't have it anymore. 

And a bit of context, I'm running Alpine on WSL2. In case you will attempt to reproduce.

**Comment by JanDeDobbeleer** [comment] 2021-11-27 14:37
@DrMagPie did you install via homebrew on linux? I'm thinking in the direction of a static vs dynamic build.

This points in that direction:

> Relase binaries should be built as staticly linked libraries so that they are completely selfcontained as mentioned here using -v -ldflags '-d -s -w' to build static binaries.

**Comment by DrMagPie** [comment] 2021-11-27 15:19
I have downloaded it from releases page

```shell
curl -fLo /usr/local/bin/oh-my-posh https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v6.17.0/posh-linux-amd64
chmod +x /usr/local/bin/oh-my-posh
```

**Comment by JanDeDobbeleer** [comment] 2021-11-27 15:47
I'll try to reproduce this in a container (and fix it as well).

**Comment by JanDeDobbeleer** [comment] 2021-11-27 20:05
@DrMagPie what's the result when installing via [homebrew](https://ohmyposh.dev/docs/linux)? I'm troubleshooting tomorrow, but this is definitely interesting to know.

**Comment by DrMagPie** [comment] 2021-11-27 21:50
I have not tried it on Linux.
Will try tomorrow.

**Comment by DrMagPie** [comment] 2021-11-28 15:44
I tried to get homebrew to work.
But failed miserably due to alpine being funky with its versions.
And probably corporate policies were sticks into the whiles.
I can try to compile it from the source, but that would be tomorrow.

**Comment by JanDeDobbeleer** [comment] 2021-11-28 18:45
@DrMagPie before you try that, can you first run `apk add libc6-compat`. That should "fix" dynamic libs on Alpine. I could reproduce the binary NOT working at all until I added the lightweight libc compatibility lib.

**Comment by DrMagPie** [comment] 2021-11-28 18:56
Noted.

Will post an update as soon as I try it.

**Comment by DrMagPie** [comment] 2021-11-29 08:21
![image](https://user-images.githubusercontent.com/23652900/143832053-7b0ca20a-259e-400e-94e9-91f91340ab5a.png)

**Comment by JanDeDobbeleer** [comment] 2021-11-29 09:07
@DrMagPie I'll provide a static build later today 👍🏻

**Comment by paulbouwer** [comment] 2022-01-19 06:43
@JanDeDobbeleer @DrMagPie - I bumped into the same issue today. I implemented the following work-around in my alpine based container that seems to be working just fine now. It might help others.

```
apk add libc6-compat gcompat --update
/usr/local/bin/oh-my-posh --init --shell bash --config ~/.oh-my-posh/az.omp.json > ~/.oh-my-posh/init.bash
sed -i 's#/lib/ld-musl-x86_64.so.1#/usr/local/bin/oh-my-posh#' ~/.oh-my-posh/init.bash
source ~/.oh-my-posh/init.bash
```

You can see this in more detail in the following PR.

[PR#8 | azure-cli/Dockerfile | Fixed glibc compat issue with oh-my-posh on alpine](https://github.com/paulbouwer/dockerfiles/pull/8/files#diff-f9da12c2eb656b78dded259a0484b4bc344dfafae2f46f3d37e883f3f74a3bb2)

**Comment by JanDeDobbeleer** [comment] 2022-01-19 12:30
#1612 can be an answer to this one.

**Comment by JanDeDobbeleer** [comment] 2022-03-05 12:11
@paulbouwer @DrMagPie given that we now have a static build (and that no other reports are getting in) I'm closing this one.

**Closed as completed by JanDeDobbeleer** 2022-03-05 12:11 UTC
Labels: 🐛 bug
