### ISSUE TITLE
Something similar to the gap filler (?) from the powerlevel10k theme. 

### ISSUE THREAD

**Issue by Pyrrhusn** [JanDeDobbeleer/oh-my-posh#1672] opened 2022-02-03 15:23 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I was wondering if something like this is possible with oh-my-posh theming. Basically the gap filler is a series of characters that forms a separation like line and also symbolically "connects" the left and right segments of the theme. As an example from the powerlevel10k theme:   

![image](https://user-images.githubusercontent.com/43817108/152372503-1fcaf9a7-bc60-4a98-97a6-3790729c44bd.png)

**Comment by JanDeDobbeleer** [comment] 2022-02-03 16:22
@IPushedU duplicate of #1472

**Closed as completed by JanDeDobbeleer** 2022-02-03 16:22 UTC
Labels: 🚀 feat
