### ISSUE TITLE
Refresh interval

### ISSUE THREAD

**Issue by Kyren223** [JanDeDobbeleer/oh-my-posh#5154] opened 2024-06-23 13:25 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

Have a global (or potentially per-block/segment) option for how often to refresh the prompt
Example:
refresh-interval: 5000 // Reload every 5000ms (5s) the prompt

This would be useful to have real-time information with things like git, battery, time etc, currently you'd have to press enter for it to re-generate the prompt to see if there are any changes

I recommend doing this as an async check for differences between the new prompt and the current prompt, and only update if there is a difference (to not have it constantly re-rendering)

**Comment by JanDeDobbeleer** [comment] 2024-06-23 14:36
Duplicate of #5036

**Closed as completed** 2024-06-23 14:36 UTC
Labels: 🚀 feat
