### ISSUE TITLE
Get-PoshThemes gives you stack trace with unknown PC error

### ISSUE THREAD

**Issue by Sharath-unravel** [JanDeDobbeleer/oh-my-posh#188] opened 2020-11-25 11:21 UTC
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Get-PoshThemes gives you stack trace with unknown PC error

### Environment

- Oh my Posh version: latest beta
- Theme: powerlevel10k
- Operating System: Windows 10
- Shell: Powershell
- Terminal: Windows Terminal Preview

### Steps to Reproduce
Get-PoshThemes

**Expected behavior:** [What you expected to happen]
You get a list of themes with example prompts
**Actual behavior:** [What actually happened]
❯ Get-PoshThemes
   __  _____ _      ___  ___       ______         _      __
  / / |  _  | |     |  \/  |       | ___ \       | |     \ \
 / /  | | | | |__   | .  . |_   _  | |_/ /__  ___| |__    \ \
< <   | | | | '_ \  | |\/| | | | | |  __/ _ \/ __| '_ \    > >
 \ \  \ \_/ / | | | | |  | | |_| | | | | (_) \__ \ | | |  / /
  \_\  \___/|_| |_| \_|  |_/\__, | \_|  \___/|___/_| |_| /_/
                             __/ |
                            |___/
============================================================================================================================================================
agnoster

Exception 0xc0000005 0x0 0x7ffc31210fff 0x28e0efa0000
PC=0x28e0efa0000

runtime: unknown pc 0x28e0efa0000
stack: frame={sp:0xc198ffe640, fp:0x0} stack=[0x0,0xc198fffe30)
000000c198ffe540:  0000028e0ec69720  000000c198ffe660
000000c198ffe550:  0000028e0ec82e30  0000028e00000030
000000c198ffe560:  0000000000000000  000000c198ffe680
000000c198ffe570:  000000c100000840  0000000000000000
000000c198ffe580:  0000000000000000  000000c100000000
000000c198ffe590:  0000000000000001  0000000000000000
000000c198ffe5a0:  000000c198ffe658  000000c198ffeca0
000000c198ffe5b0:  0000000000000001  00007ffc3102133b
000000c198ffe5c0:  0000000000000000  0000028e0ec69720
000000c198ffe5d0:  0000028e0ec66d80  00000000c0000135
000000c198ffe5e0:  0000028e0ec69720  00007ffc31020e95
000000c198ffe5f0:  0000000000000000  0000028e0ec66d80
000000c198ffe600:  0000000000000000  0000028e0ec69720
000000c198ffe610:  000000c100000000  00007ffc310100d8
000000c198ffe620:  00007ffc31167f20  00007ffc2cc9b600
000000c198ffe630:  0000000000000001  00007ffc31035c09
000000c198ffe640: <00007ffc00000001  000000c100000386
000000c198ffe650:  0000000000000000  000000c198ffe6c0
000000c198ffe660:  00007ffc31139908  00007ffc2ed01ccd
000000c198ffe670:  0000028e0ec82e30  0000028e0ec82e56
000000c198ffe680:  00000000c000007a  00007ffc31098470
000000c198ffe690:  0000028e0ec69720  00007ffc31167f20
000000c198ffe6a0:  0000028e0ec52770  0000028e0ec66d80
000000c198ffe6b0:  000130f700000004  000130f70033004d
000000c198ffe6c0:  00007ffc310100d8  0000000000000991
000000c198ffe6d0:  0000000000000000  0000028e0ec52770
000000c198ffe6e0:  00007ffc3116a590  00007ffc310100d8
000000c198ffe6f0:  0000000000000000  00007ffc31010000
000000c198ffe700:  0000000000000000  00007ffc2d14cc88
000000c198ffe710:  00007ffc2d14a168  00007ffc31167f48
000000c198ffe720:  00007ffc3117b017  00007ffc2d14d850
000000c198ffe730:  00007ffc2d140000  00007ffc3116cbd4
runtime: unknown pc 0x28e0efa0000
stack: frame={sp:0xc198ffe640, fp:0x0} stack=[0x0,0xc198fffe30)
000000c198ffe540:  0000028e0ec69720  000000c198ffe660
000000c198ffe550:  0000028e0ec82e30  0000028e00000030
000000c198ffe560:  0000000000000000  000000c198ffe680
000000c198ffe570:  000000c100000840  0000000000000000
000000c198ffe580:  0000000000000000  000000c100000000
000000c198ffe590:  0000000000000001  0000000000000000
000000c198ffe5a0:  000000c198ffe658  000000c198ffeca0
000000c198ffe5b0:  0000000000000001  00007ffc3102133b
000000c198ffe5c0:  0000000000000000  0000028e0ec69720
000000c198ffe5d0:  0000028e0ec66d80  00000000c0000135
000000c198ffe5e0:  0000028e0ec69720  00007ffc31020e95
000000c198ffe5f0:  0000000000000000  0000028e0ec66d80
000000c198ffe600:  0000000000000000  0000028e0ec69720
000000c198ffe610:  000000c100000000  00007ffc310100d8
000000c198ffe620:  00007ffc31167f20  00007ffc2cc9b600
000000c198ffe630:  0000000000000001  00007ffc31035c09
000000c198ffe640: <00007ffc00000001  000000c100000386
000000c198ffe650:  0000000000000000  000000c198ffe6c0
000000c198ffe660:  00007ffc31139908  00007ffc2ed01ccd
000000c198ffe670:  0000028e0ec82e30  0000028e0ec82e56
000000c198ffe680:  00000000c000007a  00007ffc31098470
000000c198ffe690:  0000028e0ec69720  00007ffc31167f20
000000c198ffe6a0:  0000028e0ec52770  0000028e0ec66d80
000000c198ffe6b0:  000130f700000004  000130f70033004d
000000c198ffe6c0:  00007ffc310100d8  0000000000000991
000000c198ffe6d0:  0000000000000000  0000028e0ec52770
000000c198ffe6e0:  00007ffc3116a590  00007ffc310100d8
000000c198ffe6f0:  0000000000000000  00007ffc31010000
000000c198ffe700:  0000000000000000  00007ffc2d14cc88
000000c198ffe710:  00007ffc2d14a168  00007ffc31167f48
000000c198ffe720:  00007ffc3117b017  00007ffc2d14d850
000000c198ffe730:  00007ffc2d140000  00007ffc3116cbd4
rax     0x7ffc2d14d850
rbx     0x7ffc2d14d84e
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0xc000007a
rbp     0x7ffc2cc9b600
rsp     0xc198ffe640
r8      0x0
r9      0x0
r10     0x0
r11     0x990
r12     0x7ffc31010000
r13     0x0
r14     0x0
r15     0x7ffc2d14d850
rip     0x28e0efa0000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

This just gets stuck there and if i do ctrl +c it exits to a non-prompted shell.

**Comment by JanDeDobbeleer** [comment] 2020-11-25 12:19
I can't reproduce this on MacOS, nor Windows with version 3.44.1. Can you try replacing the binary in the module's bin folder with the one in the latest release here? Maybe the download/unpack got corrupt. `0xc0000005` can imply the binary is faulty.

**Comment by JanDeDobbeleer** [comment] 2020-11-30 07:59
@Sharath-unravel are you using this on PowerShell 5 perhaps?

**Comment by JanDeDobbeleer** [comment] 2020-12-02 18:19
@Sharath-unravel I'm closing this given we now support PS5 and this bug can't be reproduced by anyone else.

**Closed as completed by JanDeDobbeleer** 2020-12-02 18:19 UTC
Labels: 🐛 bug, powershell
