### ISSUE TITLE
Error: unknown flag: --shell

### ISSUE THREAD

**Issue by nidrissi** [JanDeDobbeleer/oh-my-posh#2820] opened 2022-09-23 07:32 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After updating to v10, I get the following error in zsh every time the prompt is displayed anew:

```
Error: unknown flag: --shell
Usage:
  oh-my-posh get [shell|millis|accent] [flags]

Flags:
  -h, --help   help for get

Global Flags:
  -c, --config string   config (required)
```

I'm pretty sure this was introduced by babe425f3f4873c7a71a455d1f94031e8fee3f23.

### Theme

https://github.com/nidrissi/dotfiles/blob/main/src/config/powershell/najib.omp.json

My setup is pretty standard, in .zshrc I have:

    eval "$(oh-my-posh init zsh --config $HOME/.config/powershell/najib.omp.json)"

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```Shell
Version: 10.0.0

Segments:

ConsoleTitle(true)   -   0 ms - o314n ~ zsh>
os(true)             -   0 ms -  
session(true)        -   0 ms -  o314n
root(false)          -   0 ms -
path(true)           -   1 ms -  
node(false)          -   0 ms -
dotnet(false)        -   0 ms -
git(false)           -   0 ms -
time(true)           -   0 ms -  09:32:26 
shell(true)          -   0 ms - zsh
text(true)           -   0 ms - 
executiontime(true)  -   2 ms -  0ms
exit(true)           -   0 ms -  

Run duration: 9.0797ms

Cache path: /home/najib/.cache/oh-my-posh

Config path: /home/najib/.config/powershell/najib.omp.json

Logs:

2022/09/23 09:32:26 debug: Getenv

2022/09/23 09:32:26 Getenv duration: 9µs, args: XDG_CACHE_HOME
2022/09/23 09:32:26 CachePath duration: 24.6µs, args:
2022/09/23 09:32:26 debug: Getenv
/home/najib/.config/powershell/najib.omp.json
2022/09/23 09:32:26 Getenv duration: 6.8µs, args: POSH_THEME
2022/09/23 09:32:26 resolveConfigPath duration: 9.6µs, args:
2022/09/23 09:32:26 Init duration: 146µs, args:
2022/09/23 09:32:26 Flags duration: 100ns, args:
2022/09/23 09:32:26 config.loadConfig duration: 664.4µs, args:
2022/09/23 09:32:26 Flags duration: 0s, args:
2022/09/23 09:32:26 debug: Getenv

2022/09/23 09:32:26 Getenv duration: 1.1µs, args: OMP_CACHE_DISABLED
2022/09/23 09:32:26 Root duration: 900ns, args:
2022/09/23 09:32:26 debug: Shell
process name: zsh
2022/09/23 09:32:26 Shell duration: 323.3µs, args:
2022/09/23 09:32:26 ErrorCode duration: 100ns, args:
2022/09/23 09:32:26 debug: Getenv
Debian
2022/09/23 09:32:26 Getenv duration: 1µs, args: WSL_DISTRO_NAME
2022/09/23 09:32:26 IsWsl duration: 2.4µs, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 13.4µs, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 debug: User
najib
2022/09/23 09:32:26 User duration: 800ns, args:
2022/09/23 09:32:26 debug: Host
o314n
2022/09/23 09:32:26 Host duration: 2.4µs, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 TemplateCache duration: 384.9µs, args:
2022/09/23 09:32:26 Flags duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 1µs, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 300ns, args:
2022/09/23 09:32:26 Shell duration: 200ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 1.7µs, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 debug: Getenv

2022/09/23 09:32:26 Getenv duration: 900ns, args: SSH_CONNECTION
2022/09/23 09:32:26 debug: Getenv

2022/09/23 09:32:26 Getenv duration: 700ns, args: SSH_CLIENT
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 200ns, args:
2022/09/23 09:32:26 Shell duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 1.5µs, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 Root duration: 1µs, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 900ns, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 500ns, args:
2022/09/23 09:32:26 Flags duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 500ns, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 PathSeparator duration: 100ns, args:
2022/09/23 09:32:26 Flags duration: 0s, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 500ns, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 PathSeparator duration: 100ns, args:
2022/09/23 09:32:26 PathSeparator duration: 0s, args:
2022/09/23 09:32:26 PathSeparator duration: 0s, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 debug: Getenv
Debian
2022/09/23 09:32:26 Getenv duration: 800ns, args: WSL_DISTRO_NAME
2022/09/23 09:32:26 IsWsl duration: 11.2µs, args:
2022/09/23 09:32:26 debug: RunCommand
//wsl.localhost/Debian/home/najib
2022/09/23 09:32:26 RunCommand duration: 908.9µs, args: wslpath -m /home/najib
2022/09/23 09:32:26 StackCount duration: 100ns, args:
2022/09/23 09:32:26 DirIsWritable duration: 5.7µs, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 Shell duration: 200ns, args:
2022/09/23 09:32:26 Flags duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 9.4µs, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 500ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 700ns, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 500ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 700ns, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 debug: Getenv
Debian
2022/09/23 09:32:26 Getenv duration: 4.7µs, args: WSL_DISTRO_NAME
2022/09/23 09:32:26 IsWsl duration: 6.1µs, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 500ns, args:
2022/09/23 09:32:26 debug: RunCommand
//wsl.localhost/Debian/home/najib
2022/09/23 09:32:26 RunCommand duration: 786.3µs, args: wslpath -m /home/najib
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 debug: CommandPath
/usr/bin/git
2022/09/23 09:32:26 CommandPath duration: 18µs, args: git
2022/09/23 09:32:26 HasCommand duration: 19.3µs, args: git
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 600ns, args:
2022/09/23 09:32:26 error: HasParentFilePath
stat /.git: no such file or directory
2022/09/23 09:32:26 HasParentFilePath duration: 14.6µs, args: .git
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 800ns, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 Shell duration: 200ns, args:
2022/09/23 09:32:26 Flags duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 1µs, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 Shell duration: 100ns, args:
2022/09/23 09:32:26 Flags duration: 0s, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 200ns, args:
2022/09/23 09:32:26 Shell duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 1.1µs, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 0s, args:
2022/09/23 09:32:26 TemplateCache duration: 200ns, args:
2022/09/23 09:32:26 Shell duration: 0s, args:
2022/09/23 09:32:26 Flags duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 900ns, args:
2022/09/23 09:32:26 GOOS duration: 100ns, args:
2022/09/23 09:32:26 ExecutionTime duration: 0s, args:
2022/09/23 09:32:26 TemplateCache duration: 0s, args:
2022/09/23 09:32:26 TemplateCache duration: 300ns, args:
2022/09/23 09:32:26 Shell duration: 200ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 debug: Pwd
/home/najib
2022/09/23 09:32:26 Pwd duration: 1.4µs, args:
2022/09/23 09:32:26 GOOS duration: 0s, args:
2022/09/23 09:32:26 ErrorCode duration: 0s, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 Shell duration: 100ns, args:
2022/09/23 09:32:26 TemplateCache duration: 100ns, args:
2022/09/23 09:32:26 debug: Getenv

2022/09/23 09:32:26 Getenv duration: 1.4µs, args: XDG_CACHE_HOME
2022/09/23 09:32:26 CachePath duration: 15.2µs, args:
2022/09/23 09:32:26 Flags duration: 0s, args:
Error: unknown flag: --shell
Usage:
  oh-my-posh get [shell|millis|accent] [flags]

Flags:
  -h, --help   help for get

Global Flags:
  -c, --config string   config (required)
```

**Comment by JanDeDobbeleer** [comment] 2022-09-23 08:16
Duplicate of #2821

**Closed as completed by JanDeDobbeleer** 2022-09-23 08:16 UTC
Labels: 🐛 bug
