### ISSUE TITLE
macos bash not supported [[ -v MC_SID ]]

### ISSUE THREAD

**Issue by wishyes** [JanDeDobbeleer/oh-my-posh#3430] opened 2023-01-31 09:42 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

bash: eval: line 25: conditional binary operator expected
bash: eval: line 25: syntax error near `MC_SID'
bash: eval: line 25: `    if [[ -v MC_SID ]];then'

### Theme

M365Princess

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
[DEBUG] 17:41:24.360 shell.go:Getenv:342 → /Users/wishyes/.cache
[TRACE] 17:41:24.360 shell.go:Getenv(XDG_CACHE_HOME) - 2.736458ms
[TRACE] 17:41:24.360 shell_unix.go:CachePath() - 2.766ms
[DEBUG] 17:41:24.360 shell.go:Getenv:342 → /opt/homebrew/Cellar/oh-my-posh/14.0.0/themes/M365Princess.omp.json
[TRACE] 17:41:24.360 shell.go:Getenv(POSH_THEME) - 4.792µs
[TRACE] 17:41:24.360 shell.go:resolveConfigPath() - 9.667µs
[TRACE] 17:41:24.360 shell.go:Init() - 3.585416ms
[TRACE] 17:41:24.360 shell.go:Flags() - 42ns
[TRACE] 17:41:24.362 config.go:loadConfig() - 505.042µs
[TRACE] 17:41:24.362 shell.go:Flags() - 83ns
[DEBUG] 17:41:24.362 shell.go:Getenv:342 → NO DATA
[TRACE] 17:41:24.362 shell.go:Getenv(OMP_CACHE_DISABLED) - 3.458µs
```

**Comment by JanDeDobbeleer** [comment] 2023-01-31 10:54
@wishyes you probably need to update bash. As this is supported syntax.

**Comment by JanDeDobbeleer** [comment] 2023-01-31 12:19
duplicate of #3429

**Closed as completed by JanDeDobbeleer** 2023-01-31 12:19 UTC

**Comment by wishyes** [comment] 2023-02-01 02:08
@JanDeDobbeleer thanks, bash has been updated

**Comment by QuaCKeReD** [comment] 2023-02-10 10:06
I am getting same on brand new install (Mac mini M2), yet not on my MacBook Pro Intel, both with same bash version (except arch)

**Comment by JanDeDobbeleer** [comment] 2023-02-10 10:10
@QuaCKeReD update your bash. Apple doesn't update it anymore. It's ancient.

**Comment by QuaCKeReD** [comment] 2023-02-10 10:17
I am using Homebrew bash (latest version), and same version on both machines;

Mac mini M2;
$ which bash
/opt/homebrew/bin/bash
$ bash --version
GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)
Copyright (C) 2022 Free Software Foundation, Inc.


MacBook Pro;
$ which bash
/usr/local/bin/bash
$ bash --version
GNU bash, version 5.2.15(1)-release (x86_64-apple-darwin22.1.0)
Copyright (C) 2022 Free Software Foundation, Inc.

**Comment by QuaCKeReD** [comment] 2023-02-10 10:18
My error is slightly different than OP, and, as mentioned, only on the M2 machine;

$ reload
bash: eval: line 73: conditional binary operator expected
bash: eval: line 73: syntax error near `MC_SID'
bash: eval: line 73: `    if [[ "false" != "true" ]] || [[ -v MC_SID ]]; then'

**Comment by QuaCKeReD** [comment] 2023-02-10 10:23
for reference;

mini was on OMP 14.2.5
MacBook Pro was on OMP 13.3.0 

both now updated to 14.2.6 - same error on both machines now!

Seems whatever is causing the error was 'working' in older version that isn't now?

**Comment by QuaCKeReD** [comment] 2023-02-10 11:30
@JanDeDobbeleer, is there anything else I can provide to help identify the cause of this issue?

**Comment by QuaCKeReD** [comment] 2023-02-10 12:06
😟 just re-run setup scripts (dotfiles and brew installs) on MBP, to bring it uptown date, and now it gets same error

Still on latest bash version

**Comment by QuaCKeReD** [comment] 2023-02-10 14:33
Ahh, so fix #3415  introduced the MC_SID check 😀 

Even weirder now....

With a simple test script;
```
$ cat omp-test.sh
    if [[ "false" != "true" ]] || [[ -v MC_SID ]]; then
        echo "Match!"
    fi
```

In iTerm & Terminal.app;
```
$ . ./omp-test.sh
bash: ./omp-test.sh: line 1: conditional binary operator expected
bash: ./omp-test.sh: line 1: syntax error near `MC_SID'
bash: ./omp-test.sh: line 1: `    if [[ "false" != "true" ]] || [[ -v MC_SID ]]; then'
```

in VSCode Terminal;
```
$ . ./omp-test.sh 
Match!
```

**Comment by QuaCKeReD** [comment] 2023-02-10 14:48
OK......sorry for the posts 😟 

Despite a `which bash` showing correctly and my initial setup script running a `chsh` during setup, my login shell was still set to `/bin/bash` 😊 

So, 'update your bash' is correct, just make sure you are using that bash 🥳

**Comment by dtmilano** [comment] 2023-03-16 01:02
🧑‍🔧 Quick fix.
Where you have something like

```
eval "$(oh-my-posh init bash <your-other-options...>)"
```

replace it by

```
eval "$(oh-my-posh init bash <your-other-options...> |  sed 's|\[\[ -v MC_SID \]\]|[[ -n "$MC_SID" ]]|')"
```

I wonder who thought midnight commander is more relevant than macOS

**Comment by JanDeDobbeleer** [comment] 2023-03-16 05:04
@dtmilano or, update bash. And I was the one who decided that.

**Comment by GrimmiMeloni** [comment] 2023-08-30 20:18
I think there is a regression on this. After my last brew update I am seeing this error again in the VScode terminal.

**Comment by JanDeDobbeleer** [comment] 2023-08-30 20:27
@GrimmiMeloni this functionality hasn't changed since this conversation.

**Comment by GrimmiMeloni** [comment] 2023-08-30 20:28
My bad. Seems VScode update somehow tossed out my shell settings. On closer inspection I realized vscode was launching the OSX native 3.x bash. Added a new shell profile using the brew provided bash again. All good now.
