### ISSUE TITLE
Display Blank line when file name contains a Chinese name

### ISSUE THREAD

**Issue by ikreva** [JanDeDobbeleer/oh-my-posh#1022] opened 2021-10-03 05:38 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

If the file name contains a Chinese name, a blank line will be displayed between the Chinese file names in the file list.

<img width="802" alt="2021-10-03 133329" src="https://user-images.githubusercontent.com/69108874/135741477-4a23f375-07ed-4247-885e-887028248ab2.png">

### Version

5.6.4

### Theme

iterm2
powerline10k_rainbow

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment] 2021-10-03 05:42
@ikreva duplicate of #908, see [this](https://github.com/JanDeDobbeleer/oh-my-posh/issues/908#issuecomment-910173401) comment for the fix (but it's Powershell that has the issue, not oh-my-posh).

**Closed as completed by JanDeDobbeleer** 2021-10-03 05:42 UTC
Labels: 🐛 bug
