### ISSUE TITLE
Installing a Font does not work

### ISSUE THREAD

**Issue by SpotlightForBugs** [JanDeDobbeleer/oh-my-posh#5178] opened 2024-06-27 18:49 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\Johannes> oh-my-posh font install meslo

    You need to be administrator to install a font as system font.
    You can either run this command as administrator or specify the --user flag to install the font for your user only:

    oh-my-posh font install --user

PS C:\Users\Johannes> oh-my-posh font install meslo --user

    🌏 Downloading https://github.com/ryanoasis/nerd-fonts/releases/latest/download/meslo.zip

Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:479 +0x91
panic({0xae51a0?, 0x12eef70?})
        /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:770 +0x132
github.com/jandedobbeleer/oh-my-posh/src/font.(*main).Update(0xc000309b88, {0xb51960, 0xc000310060})
        /home/runner/work/oh-my-posh/oh-my-posh/src/font/cli.go:234 +0x3dc
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000281c00, {0xd43ae0?, 0xc000309b88?}, 0xc00002e840)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:412 +0x6c2
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000281c00)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:550 +0xa2e
github.com/jandedobbeleer/oh-my-posh/src/font.Run({0xc00000a140, 0x5}, 0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/font/cli.go:274 +0xb1
github.com/jandedobbeleer/oh-my-posh/src/cli.init.func3(0xc000280a00?, {0xc0003114d0?, 0x4?, 0xba7f42?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/font.go:57 +0x1a5
github.com/spf13/cobra.(*Command).execute(0x1310280, {0xc000311470, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x13127e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/jandedobbeleer/oh-my-posh/src/cli.Execute()
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:38 +0x1a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:6 +0xf
PS C:\Users\Johannes> ^I

### Theme

tried to install a font, made the error above

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
PS C:\Users\Johannes> oh-my-posh debug --plain

Version: 21.16.2

Shell: powershell

Prompt:

 Johannes   ~                                                                          in powershell at 20:48:25
Segments:

ConsoleTitle(true)                        -   1 ms
Session(true)                             -   0 ms
Path(true)                                -   2 ms
Status(true)                              -   1 ms
Shell(true)                               -   0 ms
Time(true)                                -   0 ms

Run duration: 29.9748ms

Cache path: C:\Users\Johannes\AppData\Local\oh-my-posh

Config path: no --config set, using default built-in configuration

Logs:

[DEBUG] 20:48:25.912 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.913 shell.go:Getenv(TERM_PROGRAM) - 1.275ms
[DEBUG] 20:48:25.913 shell.go:Getenv:326 → C:\Users\Johannes\AppData\Local
[TRACE] 20:48:25.913 shell.go:Getenv(LOCALAPPDATA) - 0s
[TRACE] 20:48:25.913 shell_windows.go:CachePath() - 0s
[DEBUG] 20:48:25.913 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.913 shell.go:Getenv(POSH_THEME) - 0s
[DEBUG] 20:48:25.913 shell.go:resolveConfigPath:246 → No config set, fallback to default config
[TRACE] 20:48:25.913 shell.go:resolveConfigPath() - 0s
[TRACE] 20:48:25.913 shell.go:Init() - 1.275ms
[TRACE] 20:48:25.913 shell.go:Flags() - 0s
[DEBUG] 20:48:25.913 config.go:loadConfig:129 → no config file specified, using default
[TRACE] 20:48:25.913 config.go:loadConfig() - 0s
[TRACE] 20:48:25.913 shell.go:Flags() - 0s
[DEBUG] 20:48:25.913 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.913 shell.go:Getenv(OMP_CACHE_DISABLED) - 0s
[TRACE] 20:48:25.913 shell_windows.go:WindowsRegistryKeyValue(HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor) - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[TRACE] 20:48:25.913 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.913 shell_windows.go:WindowsRegistryKeyValue:217 → ColorizationColor(DWORD): 0xC40078D4
[DEBUG] 20:48:25.913 shell.go:Shell:601 → no shell name provided in flags, trying to detect it
[DEBUG] 20:48:25.922 shell.go:Shell:609 → process name: powershell.exe
[TRACE] 20:48:25.922 shell.go:Shell() - 8.2789ms
[DEBUG] 20:48:25.922 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.922 shell.go:Getenv(POSH_SHELL_VERSION) - 0s
[DEBUG] 20:48:25.922 debug.go:PrintDebug:22 → Segment: Title
[DEBUG] 20:48:25.922 text.go:Render:72 → Rendering template: {{ .Shell }} in {{ .Folder }}
[TRACE] 20:48:25.922 shell_windows.go:Root() - 0s
[TRACE] 20:48:25.922 shell.go:Shell() - 0s
[TRACE] 20:48:25.922 shell.go:StatusCodes() - 0s
[TRACE] 20:48:25.922 shell_windows.go:IsWsl() - 0s
[DEBUG] 20:48:25.922 shell.go:TemplateCache:782 → environment: [3DVPATH=C:\AMD\Chipset_Software\Binaries\3D_V-Cache_Performance_Optimizer_Driver\ ACSetupSvcPort=23210 ACSvcPort=17532 ALLUSERSPROFILE=C:\ProgramData APPDATA=C:\Users\Johannes\AppData\Roaming ChocolateyInstall=C:\ProgramData\chocolatey ChocolateyLastPathUpdate=133639868664148641 CommonProgramFiles=C:\Program Files\Common Files CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files CommonProgramW6432=C:\Program Files\Common Files COMPUTERNAME=JOH-PC ComSpec=C:\WINDOWS\system32\cmd.exe DOTNET_CLI_TELEMETRY_OPTOUT=0 DriverData=C:\Windows\System32\Drivers\DriverData GOPATH=C:\Users\Johannes\go HOMEDRIVE=C: HOMEPATH=\Users\Johannes JAVA_HOME=E:\Program Files\Zulu\zulu-21\ LOCALAPPDATA=C:\Users\Johannes\AppData\Local LOGONSERVER=\\JOH-PC NUMBER_OF_PROCESSORS=16 NVAR_MODEL_DIR=C:\Program Files\NVIDIA Corporation\NVIDIA AR SDK\models NVVFX_MODEL_DIR=C:\Program Files\NVIDIA Corporation\NVIDIA Video Effects\models OneDrive=E:\OneDrive - Bischöfliches Pius-Gymnasium - Aachen OneDriveCommercial=E:\OneDrive - Bischöfliches Pius-Gymnasium - Aachen OneDriveConsumer=E:\OneDrive OS=Windows_NT Path=E:\Program Files\Zulu\zulu-21\bin\;C:\Python312\Scripts\;C:\Python312\;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\Eclipse Adoptium\jre-17.0.8.101-hotspot\bin;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;e:\program files\git\cmd;c:\programdata\chocolatey\bin;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Users\Johannes\AppData\Local\Microsoft\WindowsApps;D:\Users\Johannes\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Johannes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts;C:\Users\Johannes\go\bin;C:\Users\Johannes\AppData\Local\JetBrains\Toolbox\scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\Program Files\Git\cmd;C:\Program Files\Go\bin;C:\Program Files\nodejs\;C:\Program Files\Rust stable MSVC 1.79\bin;C:\Users\Johannes\AppData\Local\Programs\Python\Launcher\;C:\Users\Johannes\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Johannes\AppData\Local\Programs\Python\Python310\;C:\Users\Johannes\AppData\Local\Microsoft\WindowsApps;D:\Users\Johannes\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Johannes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts;C:\Users\Johannes\go\bin;C:\Users\Johannes\AppData\Local\JetBrains\Toolbox\scripts;C:\Users\Johannes\AppData\Local\Microsoft\WindowsApps;e:\Program Files (x86)\Nmap;C:\Users\Johannes\go\bin;C:\Users\Johannes\AppData\Roaming\npm;C:\Users\Johannes\AppData\Local\Programs\oh-my-posh\bin;C:\Users\Johannes\AppData\Local\Microsoft\WinGet\Links;C:\Users\Johannes\AppData\Local\gitkraken\bin PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL POSH_INSTALLER=winget POSH_THEMES_PATH=C:\Users\Johannes\AppData\Local\Programs\oh-my-posh\themes POWERSHELL_TELEMETRY_OPTOUT=0 PRELUDE_TOKEN=dac8df4cdcce7ea8f1b9f571633c4483 PROCESSOR_ARCHITECTURE=AMD64 PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD PROCESSOR_LEVEL=25 PROCESSOR_REVISION=6102 ProgramData=C:\ProgramData ProgramFiles=C:\Program Files ProgramFiles(x86)=C:\Program Files (x86) ProgramW6432=C:\Program Files PSModulePath=E:\OneDrive - Bischöfliches Pius-Gymnasium - Aachen\Dokumente\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules PUBLIC=C:\Users\Public RlsSvcPort=22112 SESSIONNAME=Console SystemDrive=C: SystemRoot=C:\WINDOWS TEMP=C:\Users\Johannes\AppData\Local\Temp TMP=C:\Users\Johannes\AppData\Local\Temp USERDOMAIN=JOH-PC USERDOMAIN_ROAMINGPROFILE=JOH-PC USERNAME=Johannes USERPROFILE=C:\Users\Johannes windir=C:\WINDOWS WSLENV=WT_SESSION:WT_PROFILE_ID: WT_PROFILE_ID={61c54bbd-c2c6-5271-96e7-009a87ff44bf} WT_SESSION=e4b5313c-be01-4b39-ba7d-d51637b5169e __PSLockDownPolicy=0]
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.922 shell.go:Pwd:356 → C:\Users\Johannes
[TRACE] 20:48:25.922 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.922 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.922 shell_windows.go:IsWsl() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[TRACE] 20:48:25.922 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.922 shell.go:User:494 → Johannes
[TRACE] 20:48:25.922 shell.go:User() - 0s
[DEBUG] 20:48:25.922 shell.go:Host:511 → JOH-PC
[TRACE] 20:48:25.923 shell.go:Host() - 546.9µs
[TRACE] 20:48:25.923 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.923 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.923 shell.go:Getenv(SHLVL) - 0s
[TRACE] 20:48:25.923 shell.go:TemplateCache() - 546.9µs
[DEBUG] 20:48:25.923 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.923 shell.go:Getenv(POSH_CURSOR_LINE) - 0s
[DEBUG] 20:48:25.923 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.923 shell.go:Getenv(POSH_CURSOR_COLUMN) - 0s
[TRACE] 20:48:25.923 shell.go:Flags() - 0s
[TRACE] 20:48:25.923 shell.go:Flags() - 0s
[TRACE] 20:48:25.923 shell.go:Shell() - 0s
[TRACE] 20:48:25.923 shell.go:Shell() - 0s
[TRACE] 20:48:25.923 shell.go:Flags() - 0s
[TRACE] 20:48:25.923 shell.go:Flags() - 0s
[TRACE] 20:48:25.923 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.923 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.923 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.923 segment.go:SetEnabled:560 → Segment: Session
[TRACE] 20:48:25.923 shell.go:Flags() - 0s
[DEBUG] 20:48:25.923 shell.go:Getenv:326 → NO DATA
[DEBUG] 20:48:25.923 properties.go:GetString:28 → {{ .Code }}
[TRACE] 20:48:25.923 shell.go:Getenv(SSH_CONNECTION) - 0s
[DEBUG] 20:48:25.923 shell.go:Getenv:326 → NO DATA
[TRACE] 20:48:25.923 shell.go:Pwd() - 0s
[TRACE] 20:48:25.923 shell.go:Getenv(SSH_CLIENT) - 0s
[TRACE] 20:48:25.923 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.923 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.923 shell.go:Flags() - 0s
[TRACE] 20:48:25.923 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.923 segment.go:SetEnabled:560 → Segment: Status
[TRACE] 20:48:25.923 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.923 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.923 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.923 segment.go:SetEnabled:560 → Segment: Root
[TRACE] 20:48:25.923 shell.go:Pwd() - 0s
[TRACE] 20:48:25.923 shell_windows.go:Root() - 0s
[DEBUG] 20:48:25.923 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:Flags() - 0s
[TRACE] 20:48:25.924 shell.go:StatusCodes() - 0s
[DEBUG] 20:48:25.924 segment.go:SetEnabled:560 → Segment: Path
[DEBUG] 20:48:25.924 text.go:Render:72 → Rendering template: {{ .Code }}
[DEBUG] 20:48:25.924 properties.go:GetBool:22 → display_cygpath: false
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:Pwd() - 0s
[TRACE] 20:48:25.924 shell.go:PathSeparator() - 0s
[TRACE] 20:48:25.924 shell.go:Pwd() - 0s
[TRACE] 20:48:25.924 shell.go:Shell() - 0s
[TRACE] 20:48:25.924 shell.go:Shell() - 0s
[TRACE] 20:48:25.924 shell.go:Flags() - 0s
[DEBUG] 20:48:25.924 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.924 segment.go:SetEnabled:560 → Segment: Git
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.924 properties.go:GetBool:22 → mapped_locations_enabled: true
[DEBUG] 20:48:25.924 properties.go:GetString:28 → 
[DEBUG] 20:48:25.924 shell.go:Getenv:326 → C:\Users\Johannes\AppData\Local
[DEBUG] 20:48:25.924 properties.go:GetString:28 → 
[TRACE] 20:48:25.924 shell.go:Getenv(LOCALAPPDATA) - 0s
[DEBUG] 20:48:25.924 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.924 properties.go:GetString:28 → ~
[DEBUG] 20:48:25.924 properties.go:GetKeyValueMap:46 → mapped_locations: map[]
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[TRACE] 20:48:25.924 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.924 properties.go:GetString:28 → NO DATA
[DEBUG] 20:48:25.924 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.924 shell.go:Pwd() - 0s
[TRACE] 20:48:25.924 shell.go:TemplateCache() - 0s
[TRACE] 20:48:25.924 shell.go:StackCount() - 0s
[TRACE] 20:48:25.924 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.924 properties.go:GetBool:22 → always_enabled: true
[TRACE] 20:48:25.924 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.925 win32_windows.go:isWriteable:299 → not current user or in group
[DEBUG] 20:48:25.925 win32_windows.go:isWriteable:303 → current user is member of S-1-5-32-544
[DEBUG] 20:48:25.925 win32_windows.go:isWriteable:311 ↓
    WRITE_DAC
    WRITE_OWNER
    SYNCHRONIZE
    DELETE
    READ_CONTROL
[DEBUG] 20:48:25.925 win32_windows.go:isWriteable:313 → user has write access
[TRACE] 20:48:25.925 shell_windows.go:DirIsWritable() - 518.2µs
[TRACE] 20:48:25.925 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.940 shell.go:CommandPath:553 → e:\program files\git\cmd\git.exe
[TRACE] 20:48:25.940 shell.go:CommandPath(git.exe) - 16.6451ms
[TRACE] 20:48:25.940 shell.go:HasCommand(git.exe) - 16.6451ms
[TRACE] 20:48:25.940 shell.go:Pwd() - 0s
[ERROR] 20:48:25.940 shell.go:HasParentFilePath:697 → CreateFile .git: The system cannot find the file specified.
[TRACE] 20:48:25.941 shell.go:HasParentFilePath(.git) - 521.7µs
[DEBUG] 20:48:25.941 properties.go:GetBool:22 → fetch_bare_info: false
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template:  {{ if gt .Code 0 }}{{ else }}{{ end }}
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template:   {{ path .Path .Location }}
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template:  {{ if .SSHSession }} {{ end }}{{ .UserName }}
[TRACE] 20:48:25.941 shell.go:TemplateCache() - 0s
[TRACE] 20:48:25.941 shell.go:TemplateCache() - 0s
[TRACE] 20:48:25.941 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: powerline
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: powerline
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: diamond
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: powerline
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: {{ if gt .Code 0 }}p:red{{ end }}
[TRACE] 20:48:25.941 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: diamond
[TRACE] 20:48:25.941 shell.go:Shell() - 0s
[TRACE] 20:48:25.941 shell.go:Shell() - 0s
[TRACE] 20:48:25.941 shell.go:Shell() - 0s
[TRACE] 20:48:25.941 shell.go:Shell() - 0s
[TRACE] 20:48:25.941 shell.go:Flags() - 0s
[TRACE] 20:48:25.941 shell.go:Flags() - 0s
[TRACE] 20:48:25.941 shell.go:Flags() - 0s
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.941 shell.go:GOOS() - 0s
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.941 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.941 segment.go:SetEnabled:560 → Segment: Node
[DEBUG] 20:48:25.941 properties.go:GetString:28 → files
[DEBUG] 20:48:25.941 segment.go:SetEnabled:560 → Segment: Time
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.941 properties.go:GetString:28 → 15:04:05
[TRACE] 20:48:25.941 shell.go:Flags() - 0s
[DEBUG] 20:48:25.941 properties.go:GetStringArray:52 → extensions: [*.js *.ts package.json .nvmrc pnpm-workspace.yaml .pnpmfile.cjs .vue]
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.941 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.941 properties.go:GetStringArray:52 → folders: []
[TRACE] 20:48:25.941 shell.go:GOOS() - 0s
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.941 segment.go:SetEnabled:560 → Segment: Python
[DEBUG] 20:48:25.941 properties.go:GetStringArray:52 → extensions: [*.py *.ipynb pyproject.toml venv.bak]
[DEBUG] 20:48:25.941 properties.go:GetStringArray:52 → folders: [.venv venv virtualenv venv-win pyenv-win]
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[DEBUG] 20:48:25.941 properties.go:GetBool:22 → home_enabled: false
[TRACE] 20:48:25.941 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.941 segment.go:SetEnabled:560 → Segment: Go
[DEBUG] 20:48:25.941 properties.go:GetBool:22 → home_enabled: false
[TRACE] 20:48:25.941 shell.go:Flags() - 0s
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.941 properties.go:GetStringArray:52 → extensions: [*.go go.mod]
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.941 shell.go:GOOS() - 0s
[DEBUG] 20:48:25.941 properties.go:GetStringArray:52 → folders: []
[DEBUG] 20:48:25.941 segment.go:SetEnabled:560 → Segment: Shell
[DEBUG] 20:48:25.941 properties.go:GetBool:22 → home_enabled: false
[TRACE] 20:48:25.941 shell.go:Pwd() - 0s
[DEBUG] 20:48:25.941 properties.go:GetKeyValueMap:46 → mapped_shell_names: map[]
[TRACE] 20:48:25.941 shell.go:Shell() - 0s
[DEBUG] 20:48:25.941 shell_windows.go:58 → C:\Users\Johannes
[TRACE] 20:48:25.941 shell.go:Flags() - 0s
[TRACE] 20:48:25.941 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: in <p:blue><b>{{ .Name }}</b></>
[DEBUG] 20:48:25.941 text.go:Render:72 → Rendering template: at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>
[TRACE] 20:48:25.942 shell.go:TemplateCache() - 0s
[TRACE] 20:48:25.942 shell.go:TemplateCache() - 0s
[DEBUG] 20:48:25.942 text.go:Render:72 → Rendering template: plain
[DEBUG] 20:48:25.942 text.go:Render:72 → Rendering template: plain
[DEBUG] 20:48:25.942 text.go:Render:72 → Rendering template: plain
[DEBUG] 20:48:25.942 text.go:Render:72 → Rendering template: plain
[DEBUG] 20:48:25.942 text.go:Render:72 → Rendering template: plain
[TRACE] 20:48:25.942 shell.go:Shell() - 0s
[TRACE] 20:48:25.942 shell.go:Shell() - 0s
[TRACE] 20:48:25.942 shell.go:Flags() - 0s
[TRACE] 20:48:25.942 shell.go:Shell() - 0s
[TRACE] 20:48:25.942 shell.go:Shell() - 0s
[DEBUG] 20:48:25.942 shell_windows.go:TerminalWidth:111 → terminal width: 120
[TRACE] 20:48:25.942 shell_windows.go:TerminalWidth() - 0s
[DEBUG] 20:48:25.942 shell.go:Getenv:326 → C:\Users\Johannes\AppData\Local
[TRACE] 20:48:25.942 shell.go:Getenv(LOCALAPPDATA) - 0s
[TRACE] 20:48:25.942 shell_windows.go:CachePath() - 0s
[TRACE] 20:48:25.942 shell.go:Flags() - 0s
PS C:\Users\Johannes>
```

**Comment by SpotlightForBugs** [comment] 2024-06-27 18:51
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/73603712/cdeeafbe-1f8c-493a-96a9-cb23a58f73e9)

**Comment by JanDeDobbeleer** [comment] 2024-06-27 20:52
@SpotlightForBugs I can't reproduce this, however I see where it fails which feels like a race condition. I'll provide a fix for this.

**Comment by SpotlightForBugs** [comment] 2024-06-27 20:53
@JanDeDobbeleer I'd love that. Thank you in advance!

Keep up the great work!

**Closed as completed** 2024-06-28 08:04 UTC
Labels: 🐛 bug
