### ISSUE TITLE
text property not defined

### ISSUE THREAD

**Issue by ForerunnerG34** [JanDeDobbeleer/oh-my-posh#2386] opened 2022-06-05 04:18 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Using latest version of oy-my-posh and many themes have this issue.
<img width="923" alt="bug" src="https://user-images.githubusercontent.com/46511735/172034817-707a7355-314c-4e59-92b1-d98df699dcd6.png">

### Theme

Multiple themes.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
!!text property not defined!!
```

**Comment by JanDeDobbeleer** [comment] 2022-06-05 06:22
@ForerunnerG34 the themes aren't updated for some reason. Can it be you still have a module import statement in your `$PROFILE`? As that could point to a different themes folder than the updated ones. Closing this as its not a bug with oh-my-posh.

**Closed as not planned** 2022-06-05 06:22 UTC
Labels: 🐛 bug

**Comment by ForerunnerG34** [comment] 2022-06-06 00:13
Correct, import module removed.
