### ISSUE TITLE
An exception occurred in custom key handler when pasting commands longer than 50 lines

### ISSUE THREAD

**Issue by DEberhardt** [JanDeDobbeleer/oh-my-posh#2979] opened 2022-10-19 12:34 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

```powershell
[2022-10-19 13:07:39]❯ $Error[0].Exception.Message
Exception calling "InvokePrompt" with "0" argument(s): "The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1."
[2022-10-19 13:07:57]❯ $Error[0].ScriptStackTrace
at <ScriptBlock>, <No file>: line 142
at PSConsoleHostReadLine, C:\Users\david.eberhardt\OneDrive - Applicable Ltd\Documents\WindowsPowerShell\Modules\PSReadline\2.2.5\PSReadLine.psm1: line 7
```

### Theme

My Custom theme with transient prompt enabled on Powershell 5.1 (also happens to occur on Powershell 7.3.0-preview8

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
[2022-10-19 13:33:11]❯ oh-my-posh debug

Version: 12.0.1

Segments:

ConsoleTitle(false)  -   1 ms -
spotify(false)       -  90 ms -
sysinfo(true)        -  91 ms -   86%
battery(true)        -  14 ms -   100%
owm(false)           -  20 ms -
time(true)           -   0 ms -  19 Oct
time(true)           -   0 ms -  13:33:11
root(false)          -   0 ms -
executiontime(false) -   0 ms -
shell(true)          -   0 ms -  pwsh
path(true)           -   0 ms -  C:  Users  david.eberhardt
git(false)           -  12 ms -
python(false)        -   0 ms -
exit(false)          -   0 ms -
text(true)           -   1 ms - ❯

Run duration: 269.7653ms

Cache path: C:\Users\david.eberhardt\AppData\Local\oh-my-posh

Config path: C:\Users\david.eberhardt\OneDrive - Applicable Ltd\Documents\PowerShell\Scripts\ParagnosterPlus2.omp.json

Logs:

2022/10/19 13:33:11 debug: Getenv
C:\Users\david.eberhardt\AppData\Local
2022/10/19 13:33:11 Getenv duration: 561.8µs, args: LOCALAPPDATA
2022/10/19 13:33:11 CachePath duration: 561.8µs, args:
2022/10/19 13:33:11 debug: Getenv
C:\Users\david.eberhardt\OneDrive - Applicable Ltd\Documents\PowerShell\Scripts\ParagnosterPlus2.omp.json
2022/10/19 13:33:11 Getenv duration: 0s, args: POSH_THEME
2022/10/19 13:33:11 debug: Shell
process name: pwsh.exe
2022/10/19 13:33:11 Shell duration: 31.5858ms, args:
2022/10/19 13:33:11 resolveConfigPath duration: 31.5858ms, args:
2022/10/19 13:33:11 Init duration: 33.2334ms, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 config.loadConfig duration: 1.6599ms, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 debug: Getenv

2022/10/19 13:33:11 Getenv duration: 4.9µs, args: OMP_CACHE_DISABLED
2022/10/19 13:33:11 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC42D7D9A
2022/10/19 13:33:11 Root duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 ErrorCode duration: 0s, args:
2022/10/19 13:33:11 IsWsl duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 debug: User
David.Eberhardt
2022/10/19 13:33:11 User duration: 0s, args:
2022/10/19 13:33:11 debug: Host
UKDELL4040
2022/10/19 13:33:11 Host duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 WindowTitle duration: 90.926ms, args: ^(Spotify.*)|(.*\s-\s.*)$
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 IsWsl duration: 0s, args:
2022/10/19 13:33:11 BatteryState duration: 9.7134ms, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 debug: HTTPRequest
GET /data/2.5/weather?q=BRISTOL,GB&units=metric&appid=3d07cc3aeda66d90243a06c9f4deac5f HTTP/1.1
Host: api.openweathermap.org
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/10/19 13:33:11 error: HTTPRequest
Get "http://api.openweathermap.org/data/2.5/weather?q=BRISTOL,GB&units=metric&appid=3d07cc3aeda66d90243a06c9f4deac5f": dial tcp: lookup api.openweathermap.org on 10.248.86.65:53: no such host
2022/10/19 13:33:11 HTTPRequest duration: 20.0778ms, args: http://api.openweathermap.org/data/2.5/weather?q=BRISTOL,GB&units=metric&appid=3d07cc3aeda66d90243a06c9f4deac5f
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 Root duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 ExecutionTime duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 PathSeparator duration: 0s, args:
2022/10/19 13:33:11 IsWsl duration: 0s, args:
2022/10/19 13:33:11 StackCount duration: 0s, args:
2022/10/19 13:33:11 DirIsWritable duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 debug: CommandPath
C:\Program Files\Git\cmd\git.exe
2022/10/19 13:33:11 CommandPath duration: 12.3607ms, args: git.exe
2022/10/19 13:33:11 HasCommand duration: 12.3607ms, args: git.exe
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/10/19 13:33:11 HasParentFilePath duration: 517.1µs, args: .git
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 debug: Getenv

2022/10/19 13:33:11 Getenv duration: 0s, args: VIRTUAL_ENV
2022/10/19 13:33:11 debug: Getenv

2022/10/19 13:33:11 Getenv duration: 0s, args: CONDA_ENV_PATH
2022/10/19 13:33:11 debug: Getenv

2022/10/19 13:33:11 Getenv duration: 0s, args: CONDA_DEFAULT_ENV
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 ErrorCode duration: 0s, args:
2022/10/19 13:33:11 ErrorCode duration: 0s, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
2022/10/19 13:33:11 debug: Pwd
C:\Users\david.eberhardt
2022/10/19 13:33:11 Pwd duration: 0s, args:
2022/10/19 13:33:11 debug: Home
H:\
2022/10/19 13:33:11 GOOS duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 TemplateCache duration: 0s, args:
2022/10/19 13:33:11 Shell duration: 0s, args:
2022/10/19 13:33:11 debug: Getenv
C:\Users\david.eberhardt\AppData\Local
2022/10/19 13:33:11 Getenv duration: 0s, args: LOCALAPPDATA
2022/10/19 13:33:11 CachePath duration: 63.1µs, args:
2022/10/19 13:33:11 Flags duration: 0s, args:
```

**Comment by DEberhardt** [comment] 2022-10-19 12:38
For Reference, I am trying to define an array of 59 users, like this:
```powershell
$UCS = @(
'sip:User1@domain.com',
'sip:User2@domain.com',
'sip:User3@domain.com',
...
'sip:User58@domain.com',
'sip:User59@domain.com'
)
```

and I get the above error.
If I paste longer text with multiple commands, this does not occur, for example

```powershell
$UCS = @(
'sip:User1@domain.com',
'sip:User2@domain.com',
'sip:User3@domain.com',
[...]
'sip:User49@domain.com'
)
$UCS += @(
'sip:User50@domain.com',
'sip:User51@domain.com',
[...]
'sip:User59@domain.com'
)
```

**Comment by JanDeDobbeleer** [comment] 2022-10-19 13:07
@DEberhardt duplicate of #2906 and an issue at PSReadLine (this one is definitely on their hands). The `InvokePrompt` function doesn't even accept parameters.

**Closed as completed** 2022-10-19 13:13 UTC
Labels: 🏝 external
