### ISSUE TITLE
slimfat theme: Cursor is behind prompt

### ISSUE THREAD

**Issue by pkropachev** [JanDeDobbeleer/oh-my-posh#5225] opened 2024-07-08 10:33 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Beginning from version `21.18.0` I faced with problem that cursor is located behind prompt in `slimfat` theme.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/34160907/058efb6b-4682-4ed0-ada2-5adb808ac733)

All is ok with version `21.17.2`.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/34160907/4ec56672-8368-4b31-8b94-024407304d42)

### Theme

slimfat

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
Version: 21.18.0

Shell: bash (5.0.17(1)-release)

Prompt:

▓   huaweikwx1252784oftdls   ~                               13:31:59  ▓
▓ ~#@❯                                                                   ❮    

Segments:

ConsoleTitle(true)                        -   1 ms
Os(true)                                  -   0 ms
Session(true)                             -   6 ms
Path(true)                                -   1 ms
Time(true)                                -   0 ms
Text(true)                                -   0 ms
Text(true)                                -   0 ms
Status(true)                              -   0 ms

Run duration: 35.631328ms

Cache path: /home/huawei/.cache/oh-my-posh

Config path: /home/huawei/.cache/oh-my-posh/themes/slimfat.omp.json

Logs:

[DEBUG] 13:31:59.335 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.335 os.go:Getenv(OMP_CACHE_DIR) - 50.564µs
[DEBUG] 13:31:59.335 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.335 os.go:Getenv(XDG_CACHE_HOME) - 5.353µs
[TRACE] 13:31:59.335 os_unix.go:CachePath() - 85.382µs
[DEBUG] 13:31:59.336 os.go:Getenv:306 → /home/huawei/.cache/oh-my-posh/themes/slimfat.omp.json
[TRACE] 13:31:59.336 os.go:Getenv(POSH_THEME) - 5.538µs
[DEBUG] 13:31:59.336 os_unix.go:Platform:87 → ubuntu
[TRACE] 13:31:59.336 os.go:resolveConfigPath() - 11.85µs
[TRACE] 13:31:59.336 os.go:Init() - 1.050188ms
[TRACE] 13:31:59.336 os.go:Flags() - 44ns
[TRACE] 13:31:59.337 load.go:loadConfig() - 672.411µs
[TRACE] 13:31:59.337 os.go:Flags() - 48ns
[DEBUG] 13:31:59.337 debug.go:44 → Terminal shell: %s shell
[DEBUG] 13:31:59.337 debug.go:44 → Terminal program: %s Unknown
[DEBUG] 13:31:59.337 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.337 os.go:Getenv(OMP_CACHE_DISABLED) - 4.016µs
[DEBUG] 13:31:59.337 os.go:Shell:581 → no shell name provided in flags, trying to detect it
[DEBUG] 13:31:59.356 os.go:Shell:589 → process name: bash
[TRACE] 13:31:59.357 os.go:Shell() - 19.700547ms
[DEBUG] 13:31:59.357 os.go:Getenv:306 → 5.0.17(1)-release
[TRACE] 13:31:59.357 os.go:Getenv(POSH_SHELL_VERSION) - 13.745µs
[DEBUG] 13:31:59.357 debug.go:PrintDebug:23 → Segment: Title
[DEBUG] 13:31:59.357 text.go:Render:73 → Rendering template: {{if .Root}}root :: {{end}}{{.Shell}} :: {{.Folder}}
[TRACE] 13:31:59.358 os_unix.go:Root() - 2.551µs
[TRACE] 13:31:59.358 os.go:Shell() - 184ns
[TRACE] 13:31:59.358 os.go:StatusCodes() - 222ns
[DEBUG] 13:31:59.358 os_unix.go:IsWsl:35 → false
[TRACE] 13:31:59.358 os_unix.go:IsWsl() - 46.701µs
[DEBUG] 13:31:59.358 os.go:TemplateCache:779 → environment: [SHELL=/bin/bash SESSION_MANAGER=local/kwx1252784oftdls:@/tmp/.ICE-unix/17188,unix/kwx1252784oftdls:/tmp/.ICE-unix/17188 QT_ACCESSIBILITY=1 COLORTERM=truecolor XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg LESS=-R GREP_COLOR=1;37;41 NVM_INC=/home/huawei/.nvm/versions/node/v20.15.0/include/node HISTCONTROL=erasedups:ignoreboth XDG_MENU_PREFIX=gnome- GNOME_DESKTOP_SESSION_ID=this-is-deprecated POSH_PID=134734 HISTSIZE= TERMINATOR_DBUS_PATH=/net/tenshu/Terminator2 LC_ADDRESS=en_US.UTF-8 JAVA_HOME=/home/huawei/.sdkman/candidates/java/current GNOME_SHELL_SESSION_MODE=ubuntu LC_NAME=en_US.UTF-8 SSH_AUTH_SOCK=/run/user/1000/keyring/ssh GRADLE_HOME=/home/huawei/.sdkman/candidates/gradle/current HISTTIMEFORMAT=%F %T  RIPGREP_CONFIG_PATH=/home/huawei/.ripgrep TERMINATOR_UUID=urn:uuid:16f718d4-d6b8-482a-a642-4d407afbe78e SDKMAN_CANDIDATES_DIR=/home/huawei/.sdkman/candidates XMODIFIERS=@im=ibus DESKTOP_SESSION=ubuntu LC_MONETARY=en_US.UTF-8 SSH_AGENT_PID=17150 OSH=/home/huawei/.oh-my-bash GTK_MODULES=gail:atk-bridge PWD=/home/huawei LOGNAME=huawei XDG_SESSION_DESKTOP=ubuntu XDG_SESSION_TYPE=x11 GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1 XAUTHORITY=/run/user/1000/gdm/Xauthority VIRTUALENVWRAPPER_VIRTUALENV=/home/huawei/.local/bin/virtualenv FZF_DEFAULT_COMMAND=git ls-files --cached --others --exclude-standard || fd --type f --type l --hidden --follow --exclude .git --exclude node_modules WINDOWPATH=2 VIRTUALENVWRAPPER_SCRIPT=/home/huawei/.local/bin/virtualenvwrapper.sh HOME=/home/huawei USERNAME=huawei IM_CONFIG_PHASE=1 LC_PAPER=en_US.UTF-8 LANG=en_US.UTF-8 LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: XDG_CURRENT_DESKTOP=ubuntu:GNOME POSH_SHELL_VERSION=5.0.17(1)-release VTE_VERSION=6003 VIRTUALENVWRAPPER_WORKON_CD=1 VIRTUAL_ENV_DISABLE_PROMPT=1 CONDA_PROMPT_MODIFIER=false VIRTUALENVWRAPPER_PYTHON=/home/huawei/tools/python/current/python INVOCATION_ID=a1bcc5cc679f4a239bcc62c0e45173d3 TERMINATOR_DBUS_NAME=net.tenshu.Terminator21a9d5db22c73a993ff0b42f64b396873 MANAGERPID=17039 BAT_THEME=gruvbox-dark NVM_DIR=/home/huawei/.nvm WORKON_HOME=/home/huawei/.virtualenvs/ LESSCLOSE=/usr/bin/lesspipe %s %s XDG_SESSION_CLASS=user TERM=xterm-256color LC_IDENTIFICATION=en_US.UTF-8 FZF_CTRL_T_COMMAND=fd --hidden --follow --exclude .git --exclude node_modules BAT_PAGER=less -R LESSOPEN=| /usr/bin/lesspipe %s USER=huawei FZF_ALT_C_COMMAND=fd --type d --hidden --follow --exclude .git --exclude node_modules VIRTUALENVWRAPPER_PROJECT_FILENAME=.project SDKMAN_DIR=/home/huawei/.sdkman DISPLAY=:0 SHLVL=1 NVM_CD_FLAGS= PAGER=less LC_TELEPHONE=en_US.UTF-8 QT_IM_MODULE=ibus LC_MEASUREMENT=en_US.UTF-8 SDKMAN_CANDIDATES_API=https://api.sdkman.io/2 DESKTOP_AUTOSTART_ID=10451ad6ff77a19c5a172042588719802100000171880016 PAPERSIZE=letter POSH_THEME=/home/huawei/.cache/oh-my-posh/themes/slimfat.omp.json LC_CTYPE=en_US.UTF-8 XDG_RUNTIME_DIR=/run/user/1000 LC_TIME=en_US.UTF-8 JOURNAL_STREAM=8:197620 XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop PATH=/home/huawei/.sdkman/candidates/java/current/bin:/home/huawei/.sdkman/candidates/gradle/current/bin:/home/huawei/.cargo/bin:/home/huawei/.local/share/bob/nvim-bin:/home/huawei/tools/bob-nvim:/home/huawei/tools/gn:/home/huawei/tools/ninja:/home/huawei/tools/curl/bin:/home/huawei/tools/ohos-toolchains:/home/huawei/tools/platform-tools:/home/huawei/tools/simpleperf:/home/huawei/tools/bpftrace:/home/huawei/tools/python/current:/home/huawei/tools:/home/huawei/.nvm/versions/node/v20.15.0/bin:/home/huawei/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/huawei/.dotnet/tools:/home/huawei/.local/share/JetBrains/Toolbox/scripts:/home/huawei/.fzf/bin VIRTUALENVWRAPPER_HOOK_DIR=/home/huawei/.virtualenvs/ GDMSESSION=ubuntu HISTFILESIZE= DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus FZF_DEFAULT_OPTS=--height 50% -1 --reverse --multi --inline-info --preview='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2> /dev/null | head -300' --preview-window='right:hidden:wrap' --bind='f3:execute(bat --style=numbers {} || less -f {}),f2:toggle-preview,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-a:select-all+accept,ctrl-y:execute-silent(echo {+} | pbcopy),ctrl-x:execute(rm -i {+})+abort' SDKMAN_PLATFORM=linuxx64 NVM_BIN=/home/huawei/.nvm/versions/node/v20.15.0/bin POWERLINE_COMMAND=oh-my-posh GIO_LAUNCHED_DESKTOP_FILE_PID=17448 GIO_LAUNCHED_DESKTOP_FILE=/home/huawei/.config/autostart/ulauncher.desktop LC_NUMERIC=en_US.UTF-8 OLDPWD=/usr/local/bin _=/usr/local/bin/oh-my-posh]
[TRACE] 13:31:59.358 os.go:GOOS() - 242ns
[DEBUG] 13:31:59.358 os.go:Pwd:336 → /home/huawei
[TRACE] 13:31:59.358 os.go:Pwd() - 47.051µs
[DEBUG] 13:31:59.358 os_unix.go:IsWsl:35 → false
[TRACE] 13:31:59.358 os_unix.go:IsWsl() - 13.483µs
[TRACE] 13:31:59.358 os.go:GOOS() - 131ns
[TRACE] 13:31:59.358 os.go:GOOS() - 108ns
[TRACE] 13:31:59.358 os.go:GOOS() - 134ns
[TRACE] 13:31:59.358 os.go:GOOS() - 182ns
[TRACE] 13:31:59.358 os.go:GOOS() - 113ns
[TRACE] 13:31:59.358 os.go:GOOS() - 109ns
[TRACE] 13:31:59.358 os.go:GOOS() - 116ns
[TRACE] 13:31:59.358 os.go:GOOS() - 111ns
[DEBUG] 13:31:59.358 os.go:User:474 → huawei
[TRACE] 13:31:59.358 os.go:User() - 11.707µs
[DEBUG] 13:31:59.358 os.go:Host:491 → kwx1252784oftdls
[TRACE] 13:31:59.358 os.go:Host() - 14.924µs
[TRACE] 13:31:59.358 os.go:GOOS() - 111ns
[DEBUG] 13:31:59.358 os_unix.go:Platform:87 → ubuntu
[DEBUG] 13:31:59.358 os.go:Getenv:306 → 1
[TRACE] 13:31:59.358 os.go:Getenv(SHLVL) - 11.26µs
[TRACE] 13:31:59.358 os.go:TemplateCache() - 667.391µs
[DEBUG] 13:31:59.358 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.358 os.go:Getenv(POSH_CURSOR_LINE) - 10.225µs
[DEBUG] 13:31:59.358 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.358 os.go:Getenv(POSH_CURSOR_COLUMN) - 9.202µs
[TRACE] 13:31:59.358 os.go:Flags() - 217ns
[TRACE] 13:31:59.358 os.go:Flags() - 179ns
[TRACE] 13:31:59.358 os.go:Shell() - 297ns
[TRACE] 13:31:59.358 os.go:Shell() - 111ns
[TRACE] 13:31:59.358 os.go:Flags() - 182ns
[TRACE] 13:31:59.359 os.go:Pwd() - 473ns
[TRACE] 13:31:59.359 os.go:GOOS() - 142ns
[DEBUG] 13:31:59.359 segment.go:SetEnabled:113 → Segment: Text
[TRACE] 13:31:59.359 os.go:TemplateCache() - 541ns
[TRACE] 13:31:59.359 os.go:Flags() - 113ns
[TRACE] 13:31:59.359 os.go:Pwd() - 256ns
[TRACE] 13:31:59.359 os.go:GOOS() - 219ns
[TRACE] 13:31:59.359 os.go:Flags() - 728ns
[TRACE] 13:31:59.359 os.go:Flags() - 280ns
[TRACE] 13:31:59.359 os.go:Pwd() - 178ns
[TRACE] 13:31:59.359 os.go:GOOS() - 143ns
[DEBUG] 13:31:59.359 segment.go:SetEnabled:113 → Segment: Session
[DEBUG] 13:31:59.359 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.359 os.go:Getenv(SSH_CONNECTION) - 32.672µs
[DEBUG] 13:31:59.359 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.359 os.go:Getenv(SSH_CLIENT) - 8.723µs
[DEBUG] 13:31:59.359 os_unix.go:Platform:87 → ubuntu
[TRACE] 13:31:59.361 os.go:Flags() - 642ns
[TRACE] 13:31:59.361 os.go:Pwd() - 932ns
[TRACE] 13:31:59.361 os.go:GOOS() - 377ns
[DEBUG] 13:31:59.361 segment.go:SetEnabled:113 → Segment: Git
[DEBUG] 13:31:59.361 segment.go:SetEnabled:113 → Segment: Root
[TRACE] 13:31:59.361 os.go:Pwd() - 725ns
[TRACE] 13:31:59.361 os.go:GOOS() - 246ns
[DEBUG] 13:31:59.361 os_unix.go:IsWsl:35 → false
[TRACE] 13:31:59.361 os_unix.go:Root() - 2.685µs
[DEBUG] 13:31:59.361 segment.go:SetEnabled:113 → Segment: Path
[TRACE] 13:31:59.361 os_unix.go:IsWsl() - 39.216µs
[TRACE] 13:31:59.361 os_unix.go:IsWsl2() - 56.439µs
[TRACE] 13:31:59.361 os.go:GOOS() - 150ns
[DEBUG] 13:31:59.361 path.go:124 → display_cygpath: false
[TRACE] 13:31:59.361 os.go:GOOS() - 208ns
[TRACE] 13:31:59.361 os.go:PathSeparator() - 231ns
[DEBUG] 13:31:59.361 os.go:CommandPath:533 → /usr/bin/git
[TRACE] 13:31:59.361 os.go:Pwd() - 328ns
[TRACE] 13:31:59.361 os.go:Flags() - 674ns
[TRACE] 13:31:59.361 os.go:Shell() - 334ns
[TRACE] 13:31:59.361 os.go:Shell() - 112ns
[DEBUG] 13:31:59.361 path.go:replaceMappedLocations:517 → mapped_locations_enabled: true
[DEBUG] 13:31:59.361 path.go:replaceMappedLocations:518 → 
[DEBUG] 13:31:59.361 path.go:replaceMappedLocations:519 → 
[TRACE] 13:31:59.361 os.go:Pwd() - 927ns
[TRACE] 13:31:59.361 os.go:GOOS() - 243ns
[DEBUG] 13:31:59.361 path.go:replaceMappedLocations:520 → ~
[TRACE] 13:31:59.361 os.go:GOOS() - 298ns
[TRACE] 13:31:59.361 os.go:CommandPath(git) - 265.879µs
[DEBUG] 13:31:59.361 segment.go:SetEnabled:113 → Segment: Os
[DEBUG] 13:31:59.361 path.go:replaceMappedLocations:525 → mapped_locations: map[]
[TRACE] 13:31:59.361 os.go:HasCommand(git) - 464.415µs
[TRACE] 13:31:59.361 os.go:GOOS() - 378ns
[TRACE] 13:31:59.361 os.go:Pwd() - 397ns
[DEBUG] 13:31:59.362 os_unix.go:Platform:87 → ubuntu
[DEBUG] 13:31:59.362 os.go:Enabled:39 → display_distro_name: false
[ERROR] 13:31:59.362 os.go:HasParentFilePath:687 → stat .git: no such file or directory
[DEBUG] 13:31:59.362 os.go:getDistroIcon:84 → 
[TRACE] 13:31:59.362 os.go:HasParentFilePath(.git) - 196.468µs
[TRACE] 13:31:59.362 os.go:TemplateCache() - 1.438µs
[DEBUG] 13:31:59.362 git.go:shouldDisplay:284 → fetch_bare_info: false
[TRACE] 13:31:59.362 os.go:GOOS() - 564ns
[TRACE] 13:31:59.362 os.go:GOOS() - 185ns
[DEBUG] 13:31:59.362 path.go:makeFolderFormatMap:841 → NO DATA
[TRACE] 13:31:59.362 os.go:Pwd() - 578ns
[TRACE] 13:31:59.362 os.go:TemplateCache() - 1.067µs
[TRACE] 13:31:59.362 os.go:StackCount() - 375ns
[TRACE] 13:31:59.362 os_unix.go:DirIsWritable(/home/huawei) - 24.023µs
[TRACE] 13:31:59.362 os.go:TemplateCache() - 547ns
[DEBUG] 13:31:59.365 os.go:RunCommand:511 → NO DATA
[TRACE] 13:31:59.365 os.go:RunCommand(who am i) - 5.935835ms
[TRACE] 13:31:59.365 os.go:TemplateCache() - 116ns
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template:   
[TRACE] 13:31:59.365 os.go:TemplateCache() - 41ns
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: <#f2f200>  </>{{ .Path }} 
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template:  {{ if ne .Env.POSH_SESSION_DEFAULT_USER .UserName }}<#77f5d6>{{ .UserName }}</><#7a7a7a></>{{ end }}<#2EEFBF>{{ .HostName }}</><#7a7a7a> </>
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template:  {{ if .WSL }} on {{ end }}{{ .Icon }}<#7a7a7a> </>
[TRACE] 13:31:59.365 os.go:TemplateCache() - 95ns
[TRACE] 13:31:59.365 os.go:TemplateCache() - 170ns
[TRACE] 13:31:59.365 os.go:TemplateCache() - 169ns
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[TRACE] 13:31:59.365 os.go:Shell() - 105ns
[TRACE] 13:31:59.365 os.go:Shell() - 20ns
[TRACE] 13:31:59.365 os.go:Shell() - 19ns
[TRACE] 13:31:59.365 os.go:Shell() - 32ns
[TRACE] 13:31:59.365 os.go:Flags() - 49ns
[TRACE] 13:31:59.365 os.go:Pwd() - 78ns
[TRACE] 13:31:59.365 os.go:GOOS() - 34ns
[DEBUG] 13:31:59.365 segment.go:SetEnabled:113 → Segment: Time
[DEBUG] 13:31:59.365 time.go:Enabled:29 → 15:04:05
[TRACE] 13:31:59.365 os.go:TemplateCache() - 77ns
[TRACE] 13:31:59.365 os.go:Flags() - 35ns
[DEBUG] 13:31:59.365 python.go:Init:61 → environment
[TRACE] 13:31:59.365 os.go:Pwd() - 43ns
[TRACE] 13:31:59.365 os.go:Flags() - 107ns
[TRACE] 13:31:59.365 os.go:GOOS() - 30ns
[DEBUG] 13:31:59.365 segment.go:SetEnabled:113 → Segment: Python
[TRACE] 13:31:59.365 os.go:Pwd() - 89ns
[TRACE] 13:31:59.365 os.go:GOOS() - 33ns
[DEBUG] 13:31:59.365 language.go:Enabled:109 → extensions: [*.py *.ipynb pyproject.toml venv.bak]
[DEBUG] 13:31:59.365 segment.go:SetEnabled:113 → Segment: Node
[DEBUG] 13:31:59.365 language.go:Enabled:110 → folders: [.venv venv virtualenv venv-win pyenv-win]
[DEBUG] 13:31:59.365 language.go:Enabled:117 → home_enabled: false
[TRACE] 13:31:59.365 os.go:Pwd() - 31ns
[DEBUG] 13:31:59.365 language.go:Enabled:109 → extensions: [*.js *.ts package.json .nvmrc pnpm-workspace.yaml .pnpmfile.cjs .vue]
[DEBUG] 13:31:59.365 language.go:Enabled:110 → folders: []
[TRACE] 13:31:59.365 os.go:Flags() - 21ns
[DEBUG] 13:31:59.365 language.go:Enabled:117 → home_enabled: false
[TRACE] 13:31:59.365 os.go:Pwd() - 36ns
[TRACE] 13:31:59.365 os.go:Pwd() - 32ns
[TRACE] 13:31:59.365 os.go:GOOS() - 29ns
[DEBUG] 13:31:59.365 segment.go:SetEnabled:113 → Segment: Dotnet
[TRACE] 13:31:59.365 os.go:Flags() - 109ns
[TRACE] 13:31:59.365 os.go:Pwd() - 86ns
[DEBUG] 13:31:59.365 language.go:Enabled:109 → extensions: [*.cs *.csx *.vb *.sln *.slnf *.csproj *.vbproj *.fs *.fsx *.fsproj global.json]
[TRACE] 13:31:59.365 os.go:GOOS() - 35ns
[DEBUG] 13:31:59.365 language.go:Enabled:110 → folders: []
[DEBUG] 13:31:59.365 language.go:Enabled:117 → home_enabled: false
[DEBUG] 13:31:59.365 segment.go:SetEnabled:113 → Segment: Text
[TRACE] 13:31:59.365 os.go:Pwd() - 40ns
[TRACE] 13:31:59.365 os.go:TemplateCache() - 96ns
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template:  {{ .CurrentDate | date .Format }}<#007ACC>  </>
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template:   
[TRACE] 13:31:59.365 os.go:TemplateCache() - 113ns
[TRACE] 13:31:59.365 os.go:TemplateCache() - 119ns
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.365 text.go:Render:73 → Rendering template: diamond
[DEBUG] 13:31:59.369 os_unix.go:TerminalWidth:80 → terminal width: 80
[TRACE] 13:31:59.369 os_unix.go:TerminalWidth() - 4.042762ms
[TRACE] 13:31:59.369 os.go:Shell() - 51ns
[TRACE] 13:31:59.369 os.go:Shell() - 27ns
[TRACE] 13:31:59.369 os.go:Shell() - 19ns
[TRACE] 13:31:59.369 os.go:Shell() - 20ns
[TRACE] 13:31:59.369 os.go:Flags() - 52ns
[TRACE] 13:31:59.369 os.go:Pwd() - 72ns
[TRACE] 13:31:59.369 os.go:GOOS() - 35ns
[DEBUG] 13:31:59.369 segment.go:SetEnabled:113 → Segment: Text
[TRACE] 13:31:59.369 os.go:TemplateCache() - 158ns
[DEBUG] 13:31:59.369 text.go:Render:73 → Rendering template:  ~#@❯ 
[TRACE] 13:31:59.369 os.go:Shell() - 29ns
[DEBUG] 13:31:59.369 text.go:Render:73 → Rendering template: plain
[TRACE] 13:31:59.369 os.go:Shell() - 49ns
[TRACE] 13:31:59.369 os.go:Shell() - 20ns
[TRACE] 13:31:59.369 os.go:Shell() - 19ns
[TRACE] 13:31:59.369 os.go:Shell() - 20ns
[DEBUG] 13:31:59.369 block.go:InitPlain:65 → Terminal shell: %s shell
[DEBUG] 13:31:59.369 block.go:InitPlain:65 → Terminal program: %s Unknown
[DEBUG] 13:31:59.369 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.369 os.go:Getenv(OMP_CACHE_DISABLED) - 1.941µs
[TRACE] 13:31:59.369 os.go:Flags() - 64ns
[DEBUG] 13:31:59.369 status.go:Init:53 → {{ .Code }}
[TRACE] 13:31:59.369 os.go:Pwd() - 30ns
[TRACE] 13:31:59.369 os.go:GOOS() - 31ns
[DEBUG] 13:31:59.369 segment.go:SetEnabled:113 → Segment: Status
[TRACE] 13:31:59.369 os.go:StatusCodes() - 42ns
[DEBUG] 13:31:59.370 text.go:Render:73 → Rendering template: {{ .Code }}
[TRACE] 13:31:59.370 os.go:Flags() - 126ns
[TRACE] 13:31:59.370 os.go:Flags() - 106ns
[TRACE] 13:31:59.370 os.go:Pwd() - 73ns
[TRACE] 13:31:59.370 os.go:Pwd() - 151ns
[TRACE] 13:31:59.370 os.go:GOOS() - 48ns
[TRACE] 13:31:59.370 os.go:GOOS() - 56ns
[DEBUG] 13:31:59.370 segment.go:SetEnabled:113 → Segment: Text
[DEBUG] 13:31:59.370 executiontime.go:Enabled:57 → always_enabled: false
[TRACE] 13:31:59.370 os.go:TemplateCache() - 213ns
[TRACE] 13:31:59.370 os.go:ExecutionTime() - 99ns
[DEBUG] 13:31:59.370 executiontime.go:Enabled:59 → threshold: 500.000000
[TRACE] 13:31:59.370 os.go:TemplateCache() - 142ns
[DEBUG] 13:31:59.370 status.go:Enabled:42 → always_enabled: true
[TRACE] 13:31:59.370 os.go:TemplateCache() - 52ns
[DEBUG] 13:31:59.370 text.go:Render:73 → Rendering template:   {{ if gt .Code 0 }}{{ .Code }}{{ end }} 
[DEBUG] 13:31:59.370 text.go:Render:73 → Rendering template:  ❮ 
[TRACE] 13:31:59.370 os.go:TemplateCache() - 189ns
[DEBUG] 13:31:59.370 text.go:Render:73 → Rendering template: plain
[DEBUG] 13:31:59.370 text.go:Render:73 → Rendering template: plain
[DEBUG] 13:31:59.370 text.go:Render:73 → Rendering template: {{ if gt .Code 0 }}#E84855{{ end }}
[TRACE] 13:31:59.371 os.go:TemplateCache() - 76ns
[DEBUG] 13:31:59.371 text.go:Render:73 → Rendering template: plain
[DEBUG] 13:31:59.371 text.go:Render:73 → Rendering template: {{ if gt .Code 0 }}#E84855{{ end }}
[TRACE] 13:31:59.371 os.go:TemplateCache() - 71ns
[TRACE] 13:31:59.371 os.go:Shell() - 63ns
[TRACE] 13:31:59.371 os.go:Shell() - 33ns
[TRACE] 13:31:59.371 os.go:Flags() - 44ns
[TRACE] 13:31:59.371 os.go:Shell() - 21ns
[TRACE] 13:31:59.371 os.go:Shell() - 22ns
[DEBUG] 13:31:59.371 os_unix.go:TerminalWidth:60 → terminal width: 80
[TRACE] 13:31:59.371 os_unix.go:TerminalWidth() - 2.786µs
[DEBUG] 13:31:59.371 primary.go:Primary:108 → Terminal shell: %s shell
[DEBUG] 13:31:59.371 primary.go:Primary:108 → Terminal program: %s Unknown
[DEBUG] 13:31:59.371 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.371 os.go:Getenv(OMP_CACHE_DIR) - 2.562µs
[DEBUG] 13:31:59.371 os.go:Getenv:306 → NO DATA
[TRACE] 13:31:59.371 os.go:Getenv(XDG_CACHE_HOME) - 1.797µs
[TRACE] 13:31:59.371 os_unix.go:CachePath() - 15.751µs
[TRACE] 13:31:59.371 os.go:Flags() - 21ns
```

**Comment by JanDeDobbeleer** [comment] 2024-07-08 11:39
duplicate of #5221

**Closed as completed by JanDeDobbeleer** 2024-07-08 11:39 UTC
Labels: 🐛 bug
