### ISSUE TITLE
14.19.5 fatal error rendering path segment:runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by skygunner** [JanDeDobbeleer/oh-my-posh#3646] opened 2023-03-28 12:38 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

```Shell
`
  ubuntu   nginx    rm error.log                                                                                                                                                               in bash at 22:30:00
rm: remove write-protected regular file 'error.log'? ^C
  ubuntu   nginx    sudo rm error.log                                                                                                                                                          in bash at 22:30:05

oh-my-posh fatal error rendering path segment:runtime error: invalid memory address or nil pointer dereference

goroutine 19 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/src/runtime/debug/stack.go:24 +0x65
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:453 +0x58
panic({0xbaeac0, 0x17e3bc0})
        /opt/hostedtoolcache/go/src/runtime/panic.go:884 +0x212
strings.IndexByte(...)
        /opt/hostedtoolcache/go/src/strings/strings.go:114
strings.Index({0x0?, 0x203000?}, {0xc633b2?, 0x5?})
        /opt/hostedtoolcache/go/src/strings/strings.go:1109 +0x169
strings.genSplit({0x0, 0xe}, {0xc633b2, 0x1}, 0x1, 0x30?)
        /opt/hostedtoolcache/go/src/strings/strings.go:254 +0x11d
strings.SplitAfterN(...)
        /opt/hostedtoolcache/go/src/strings/strings.go:293
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).parsePath(0xc000090000, {0x0, 0xe})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:514 +0x285
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).replaceMappedLocations(0xc000090000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:431 +0x67b
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).setPaths(0xc000090000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:103 +0x14b
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).Enabled(0xc000090000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:78 +0x25
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled(0xc0002ce1a0, {0xdceaf8, 0xc000187b00})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:473 +0x184
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:111 +0x6a
created by github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:109 +0x98
`
```

### Theme

https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
`

Version: 14.19.5

Shell: bash (5.1.16(1)-release)

Segments:

ConsoleTitle(true)                        -   0 ms - bash in backup
session(true)                             -   0 ms -   user 
path(true)                                -   0 ms -   backup 
git(false)                                -   0 ms - 
root(false)                               -   0 ms - 
exit(true)                                -   1 ms -   
node(false)                               -   0 ms - 
go(false)                                 -   0 ms - 
python(false)                             -   0 ms - 
shell(true)                               -   0 ms - in bash 
time(true)                                -   0 ms - at 22:35:59

Run duration: 6.324935ms

Cache path: /home/user/.cache/oh-my-posh

Config path: 

Logs:

[DEBUG] 22:35:59.289 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.289 shell.go:Getenv(TERM_PROGRAM) - 32.681µs
[DEBUG] 22:35:59.289 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.289 shell.go:Getenv(XDG_CACHE_HOME) - 4.24µs
[TRACE] 22:35:59.289 shell_unix.go:CachePath() - 24.92µs
[DEBUG] 22:35:59.291 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.291 shell.go:Getenv(POSH_THEME) - 7.6µs
[DEBUG] 22:35:59.291 shell.go:resolveConfigPath:324 → No config set, fallback to default config
[TRACE] 22:35:59.291 shell.go:resolveConfigPath() - 29.88µs
[TRACE] 22:35:59.291 shell.go:Init() - 1.580414ms
[TRACE] 22:35:59.291 shell.go:Flags() - 40ns
[DEBUG] 22:35:59.291 config.go:loadConfig:105 → no config file specified, using default
[TRACE] 22:35:59.291 config.go:loadConfig() - 63.801µs
[TRACE] 22:35:59.291 shell.go:Flags() - 40ns
[DEBUG] 22:35:59.291 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.291 shell.go:Getenv(OMP_CACHE_DISABLED) - 4.64µs
[DEBUG] 22:35:59.291 shell.go:Shell:641 → process name: bash
[TRACE] 22:35:59.291 shell.go:Shell() - 529.844µs
[DEBUG] 22:35:59.291 shell.go:Getenv:392 → 5.1.16(1)-release
[TRACE] 22:35:59.291 shell.go:Getenv(POSH_SHELL_VERSION) - 7.96µs
[TRACE] 22:35:59.292 shell_unix.go:Root() - 2.72µs
[TRACE] 22:35:59.292 shell.go:Shell() - 120ns
[TRACE] 22:35:59.292 shell.go:ErrorCode() - 40ns
[DEBUG] 22:35:59.292 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.292 shell.go:Getenv(WSL_DISTRO_NAME) - 4.44µs
[TRACE] 22:35:59.292 shell_unix.go:IsWsl() - 7.28µs
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.292 shell.go:Pwd:420 → NO DATA
[TRACE] 22:35:59.292 shell.go:Pwd() - 17.081µs
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.292 shell.go:User:545 → user
[TRACE] 22:35:59.292 shell.go:User() - 6.8µs
[DEBUG] 22:35:59.292 shell.go:Host:557 → ocsydamp.palmit.au
[TRACE] 22:35:59.292 shell.go:Host() - 5.72µs
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.292 shell_unix.go:Platform:63 → ubuntu
[TRACE] 22:35:59.292 shell.go:TemplateCache() - 133.121µs
[TRACE] 22:35:59.292 shell.go:Flags() - 40ns
[DEBUG] 22:35:59.292 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.292 shell.go:Pwd() - 3.56µs
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.292 shell.go:Getenv:392 → 220.233.6.9 10544 10.0.0.121 527
[TRACE] 22:35:59.292 shell.go:Getenv(SSH_CONNECTION) - 3.04µs
[TRACE] 22:35:59.292 shell.go:TemplateCache() - 80ns
[TRACE] 22:35:59.292 shell.go:TemplateCache() - 120ns
[TRACE] 22:35:59.292 shell.go:Shell() - 80ns
[DEBUG] 22:35:59.292 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.292 shell.go:Pwd() - 4.04µs
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.292 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.292 shell.go:Pwd() - 5.441µs
[TRACE] 22:35:59.292 shell.go:Shell() - 40ns
[TRACE] 22:35:59.292 shell.go:Shell() - 80ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 80ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 80ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 80ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 80ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 80ns
[TRACE] 22:35:59.292 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[TRACE] 22:35:59.292 shell.go:PathSeparator() - 40ns
[DEBUG] 22:35:59.292 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.292 shell.go:Pwd() - 2.76µs
[DEBUG] 22:35:59.292 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.292 shell.go:Getenv(WSL_DISTRO_NAME) - 2.32µs
[TRACE] 22:35:59.292 shell_unix.go:IsWsl() - 4.76µs
[TRACE] 22:35:59.292 shell.go:StackCount() - 80ns
[TRACE] 22:35:59.292 shell_unix.go:DirIsWritable(/home/user/backup) - 12.561µs
[TRACE] 22:35:59.292 shell.go:TemplateCache() - 80ns
[TRACE] 22:35:59.292 shell.go:TemplateCache() - 160ns
[TRACE] 22:35:59.293 shell.go:Shell() - 80ns
[DEBUG] 22:35:59.293 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.293 shell.go:Pwd() - 4.44µs
[TRACE] 22:35:59.293 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.293 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.293 shell.go:Getenv(WSL_DISTRO_NAME) - 2.56µs
[TRACE] 22:35:59.293 shell_unix.go:IsWsl() - 5.08µs
[TRACE] 22:35:59.293 shell_unix.go:IsWsl2() - 7.48µs
[TRACE] 22:35:59.293 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.293 shell.go:CommandPath:596 → /usr/bin/git
[TRACE] 22:35:59.293 shell.go:CommandPath(git) - 51.96µs
[TRACE] 22:35:59.293 shell.go:HasCommand(git) - 59.8µs
[DEBUG] 22:35:59.293 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.293 shell.go:Pwd() - 2.84µs
[ERROR] 22:35:59.293 shell.go:HasParentFilePath:729 → stat .git: no such file or directory
[TRACE] 22:35:59.293 shell.go:HasParentFilePath(.git) - 43.281µs
[DEBUG] 22:35:59.293 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.293 shell.go:Pwd() - 2.92µs
[TRACE] 22:35:59.293 shell.go:GOOS() - 80ns
[TRACE] 22:35:59.293 shell_unix.go:Root() - 1.32µs
[DEBUG] 22:35:59.293 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.293 shell.go:Pwd() - 2.72µs
[TRACE] 22:35:59.293 shell.go:GOOS() - 80ns
[TRACE] 22:35:59.293 shell.go:ErrorCode() - 80ns
[TRACE] 22:35:59.293 shell.go:TemplateCache() - 80ns
[TRACE] 22:35:59.294 shell.go:TemplateCache() - 400ns
[TRACE] 22:35:59.294 shell.go:Shell() - 120ns
[TRACE] 22:35:59.294 shell.go:TemplateCache() - 120ns
[TRACE] 22:35:59.294 shell.go:Flags() - 80ns
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 4.16µs
[TRACE] 22:35:59.294 shell.go:GOOS() - 80ns
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 3.161µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.8µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(*.js) - 77.16µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.88µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(*.ts) - 28.52µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.8µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(package.json) - 19.92µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.76µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(.nvmrc) - 12.48µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.8µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(pnpm-workspace.yaml) - 13.28µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.76µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(.pnpmfile.cjs) - 12.12µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.72µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(.npmrc) - 12.16µs
[DEBUG] 22:35:59.294 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.294 shell.go:Pwd() - 2.76µs
[DEBUG] 22:35:59.294 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.294 shell.go:HasFiles(.vue) - 11.96µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.88µs
[TRACE] 22:35:59.295 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.841µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.6µs
[DEBUG] 22:35:59.295 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.295 shell.go:HasFiles(*.go) - 26.96µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.72µs
[DEBUG] 22:35:59.295 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.295 shell.go:HasFiles(go.mod) - 12.76µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 6.48µs
[TRACE] 22:35:59.295 shell.go:GOOS() - 40ns
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.72µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 3µs
[DEBUG] 22:35:59.295 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.295 shell.go:HasFiles(*.py) - 27µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.84µs
[DEBUG] 22:35:59.295 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.295 shell.go:HasFiles(*.ipynb) - 25.921µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 4.08µs
[DEBUG] 22:35:59.295 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.295 shell.go:HasFiles(pyproject.toml) - 14.08µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.6µs
[DEBUG] 22:35:59.295 shell.go:HasFiles:441 → false
[TRACE] 22:35:59.295 shell.go:HasFiles(venv.bak) - 14.88µs
[DEBUG] 22:35:59.295 shell.go:HasFolder:484 → false
[TRACE] 22:35:59.295 shell.go:HasFolder(.venv) - 6.64µs
[DEBUG] 22:35:59.295 shell.go:HasFolder:484 → false
[TRACE] 22:35:59.295 shell.go:HasFolder(venv) - 5.84µs
[DEBUG] 22:35:59.295 shell.go:HasFolder:484 → false
[TRACE] 22:35:59.295 shell.go:HasFolder(virtualenv) - 5.8µs
[DEBUG] 22:35:59.295 shell.go:HasFolder:484 → false
[TRACE] 22:35:59.295 shell.go:HasFolder(env) - 5.68µs
[DEBUG] 22:35:59.295 shell.go:HasFolder:484 → false
[TRACE] 22:35:59.295 shell.go:HasFolder(venv-win) - 5.68µs
[DEBUG] 22:35:59.295 shell.go:HasFolder:484 → false
[TRACE] 22:35:59.295 shell.go:HasFolder(pyenv-win) - 10.92µs
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 2.96µs
[TRACE] 22:35:59.295 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.295 shell.go:Shell() - 120ns
[TRACE] 22:35:59.295 shell.go:Flags() - 80ns
[TRACE] 22:35:59.295 shell.go:TemplateCache() - 200ns
[TRACE] 22:35:59.295 shell.go:TemplateCache() - 80ns
[TRACE] 22:35:59.295 shell.go:Shell() - 160ns
[DEBUG] 22:35:59.295 shell.go:Pwd:400 → /home/user/backup
[TRACE] 22:35:59.295 shell.go:Pwd() - 3.88µs
[TRACE] 22:35:59.295 shell.go:GOOS() - 40ns
[TRACE] 22:35:59.295 shell.go:TemplateCache() - 80ns
[TRACE] 22:35:59.295 shell.go:TemplateCache() - 80ns
[TRACE] 22:35:59.295 shell.go:Shell() - 120ns
[DEBUG] 22:35:59.295 shell.go:Getenv:392 → NO DATA
[TRACE] 22:35:59.295 shell.go:Getenv(XDG_CACHE_HOME) - 3.32µs
[TRACE] 22:35:59.295 shell_unix.go:CachePath() - 24.8µs
[TRACE] 22:35:59.295 shell.go:Flags() - 120ns

`
```

**Comment by JanDeDobbeleer** [comment] 2023-03-28 13:32
@skygunner what config are you using? I can't explain this as it uses primitives and not objects.

**Comment by skygunner** [comment] 2023-03-30 07:46
> @skygunner what config are you using? I can't explain this as it uses primitives and not objects.

Just default config, no custom config at all.

**Comment by skygunner** [comment] 2023-03-30 07:49
@JanDeDobbeleer I got another crash today. 
My previous version is about 14.13 I think, that one runs for months no problem. 
14.19 I have one crash a day so it could be something

```Shell

  ubuntu   log    cd ~                                                                                                                                  in bash at 17:45:12
  ubuntu   ~    ls                                                                                                                                      in bash at 17:45:15
clear.sh*                           fail2sql/            hardening/                lsyncd/      Packages    pg-patroni-etcd-haproxy/  redis-stable.tar.gz
crowdsec-firewall-bouncer-v0.0.25/  fail2sql-1.0.tar.gz  libmodsecurity.so.3.0.8*  maxmind.dat  Packages.1  redis-stable/             server-init/
c
oh-my-posh fatal error rendering path segment:runtime error: invalid memory address or nil pointer dereference

goroutine 7 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/src/runtime/debug/stack.go:24 +0x65
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:453 +0x58
panic({0xbaeac0, 0x17e3bc0})
        /opt/hostedtoolcache/go/src/runtime/panic.go:884 +0x212
strings.IndexByte(...)
        /opt/hostedtoolcache/go/src/strings/strings.go:114
strings.Index({0x0?, 0x400000?}, {0xc633b2?, 0x5?})
        /opt/hostedtoolcache/go/src/strings/strings.go:1109 +0x169
strings.genSplit({0x0, 0xc}, {0xc633b2, 0x1}, 0x1, 0x30?)
        /opt/hostedtoolcache/go/src/strings/strings.go:254 +0x11d
strings.SplitAfterN(...)
        /opt/hostedtoolcache/go/src/strings/strings.go:293
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).parsePath(0xc000280000, {0x0, 0xc})
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:514 +0x285
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).replaceMappedLocations(0xc000280000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:431 +0x67b
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).setPaths(0xc000280000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:103 +0x14b
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Path).Enabled(0xc000280000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/path.go:78 +0x25
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled(0xc0000fb380, {0xdceaf8, 0xc0000f3b00})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:473 +0x184
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:111 +0x6a
created by github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:109 +0x98



oh-my-posh fatal error rendering session segment:runtime error: invalid memory address or nil pointer dereference

goroutine 6 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/src/runtime/debug/stack.go:24 +0x65
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:453 +0x58
panic({0xbaeac0, 0x17e3bc0})
        /opt/hostedtoolcache/go/src/runtime/panic.go:884 +0x212
strings.HasPrefix(...)
        /opt/hostedtoolcache/go/src/strings/strings.go:454
github.com/jandedobbeleer/oh-my-posh/src/platform.ReplaceHomeDirPrefixWithTilde({0xdceaf8, 0xc0000f3b00}, {0x0, 0xc})
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:962 +0x5e
github.com/jandedobbeleer/oh-my-posh/src/platform.(*Shell).TemplateCache(0xc0000f3b00)
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:790 +0x3f2
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled(0xc0000fb1e0, {0xdceaf8, 0xc0000f3b00})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:475 +0x1b0
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:111 +0x6a
created by github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:109 +0x98



oh-my-posh fatal error rendering git segment:runtime error: invalid memory address or nil pointer dereference

goroutine 8 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/src/runtime/debug/stack.go:24 +0x65
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:453 +0x58
panic({0xbaeac0, 0x17e3bc0})
        /opt/hostedtoolcache/go/src/runtime/panic.go:884 +0x212
os.dirFS.join({0x0, 0xc}, {0xc63fd4, 0x4})
        /opt/hostedtoolcache/go/src/os/file.go:685 +0x126
os.dirFS.Stat({0x0?, 0xbbe380?}, {0xc63fd4, 0x4})
        /opt/hostedtoolcache/go/src/os/file.go:662 +0x2c
io/fs.Stat({0xdbd1a0, 0xc000286060}, {0xc63fd4, 0x4})
        /opt/hostedtoolcache/go/src/io/fs/stat.go:22 +0x167
github.com/jandedobbeleer/oh-my-posh/src/platform.(*Shell).HasParentFilePath(0xc0000f3b00, {0xc63fd4, 0x4})
        /home/runner/work/oh-my-posh/oh-my-posh/src/platform/shell.go:695 +0x133
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Git).shouldDisplay(0xc0002ae000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/git.go:252 +0x5a
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Git).Enabled(0xc0002ae000)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/git.go:149 +0x9e
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Segment).SetEnabled(0xc0000fb520, {0xdceaf8, 0xc0000f3b00})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:473 +0x184
github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:111 +0x6a
created by github.com/jandedobbeleer/oh-my-posh/src/engine.(*Block).setEnabledSegments
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:109 +0x98

```

**Comment by JanDeDobbeleer** [comment] 2023-03-30 12:36
@skygunner can you try again on latest? I believe it always fails on trying to get the working directory due to a race condition.

**Comment by JanDeDobbeleer** [comment] 2023-04-03 13:44
@skygunner any update?

**Comment by skygunner** [comment] 2023-04-03 23:06
Hi no problem so far on various machines with 14.25.0
But I do got a different crash something when I pressed too fast when the install script start presenting the font selection after run
oh-my-posh font install

I lost the crash log

**Comment by JanDeDobbeleer** [comment] 2023-04-04 04:50
@skygunner thanks, I'm going to close this one then. If the other issue happens again, feel free to create a new issue.

**Closed as completed by JanDeDobbeleer** 2023-04-04 04:50 UTC
Labels: 🐛 bug, 🤷🏽 can't reproduce

**Comment by JanDeDobbeleer** [comment] 2023-04-04 05:07
@skygunner https://github.com/JanDeDobbeleer/oh-my-posh/pull/3671, I could reproduce a crash.

**Comment by mavaddat** [comment] 2023-05-04 17:28
I was able to get this error when running `oh-my-posh font install`.

```sh
oh-my-posh font install                       
    ⢿  Downloading font list

Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /opt/hostedtoolcache/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:402 +0x95
panic({0x12a9300, 0x1f15b20})
        /opt/hostedtoolcache/go/src/runtime/panic.go:890 +0x263
github.com/jandedobbeleer/oh-my-posh/src/font.(*main).Update(0xc0000d61b0, {0x1300d80?, 0xc0004002d0?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/font/cli.go:237 +0x6b4
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0000c00b0, {0x14c7200?, 0xc0000d61b0?}, 0xa84d2a?)
        /opt/hostedtoolcache/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:343 +0x60a
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0000c00b0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:465 +0x81d
github.com/jandedobbeleer/oh-my-posh/src/font.Run({0x0, 0x0}, 0x0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/font/cli.go:273 +0x9e
github.com/jandedobbeleer/oh-my-posh/src/cli.glob..func10(0x1f23b00?, {0xc000090140?, 0x1?, 0x1?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/font.go:41 +0x125
github.com/spf13/cobra.(*Command).execute(0x1f23b00, {0xc0000900f0, 0x1, 0x1})
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f23260)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/jandedobbeleer/oh-my-posh/src/cli.Execute({0x14bf480?, 0xc000066000?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/cli/root.go:41 +0x4a
main.main()
        /home/runner/work/oh-my-posh/oh-my-posh/src/main.go:10 +0x27
```

Screenshot:

![image](https://user-images.githubusercontent.com/5055400/236281881-a46a0281-4ca7-453c-a7ff-bf1d17e4c7e2.png)

Subjectively, I sort of ran the `oh-my-posh font install` a little bit fast after the previous `oh-my-posh font install` (impatience) when it complained above.

**Comment by JanDeDobbeleer** [comment] 2023-05-04 17:59
@mavaddat same error message, different cause. I'll have a look.
